// const { drinks } = require('./allDrinks.js');
const request = require('request');

//Mongoose:
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/openbar', {useNewUrlParser: true, useUnifiedTopology: true });

var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
  // we're connected!
  console.log('we are connected');

});

var ingredientSchema = new mongoose.Schema({
  Vodka: String,
  Gin: String,
  Rum: String,
  Tequila: String,
  Scotch: String,
  Absolut_Kurant: String,
  Absolut_Peppar: String,
  Absolut_Vodka: String,
  Advocaat: String,
  Aejo_Rum: String,
  Aftershock: String,
  Agave_Syrup: String,
  Ale: String,
  Allspice: String,
  Almond_Extract: String,
  Almond_Flavoring: String,
  Almond: String,
  Amaretto: String,
  Angelica_Root: String,
  Angostura_Bitters: String,
  Anis: String,
  Anise: String,
  Anisette: String,
  Aperol: String,
  Apfelkorn: String,
  Apple_Brandy: String,
  Apple_Cider: String,
  Apple_Juice: String,
  Apple_Schnapps: String,
  Apple: String,
  Applejack: String,
  Apricot_Brandy: String,
  Apricot_Nectar: String,
  Apricot: String,
  Aquavit: String,
  Asafoetida: String,
  Añejo_Rum: String,
  Bacardi_Limon: String,
  Bacardi: String,
  Baileys_Irish_Cream: String,
  Banana_Liqueur: String,
  Banana_Rum: String,
  Banana_Syrup: String,
  Banana: String,
  Barenjager: String,
  Basil: String,
  Beef_Stock: String,
  Beer: String,
  Benedictine: String,
  Berries: String,
  Bitter_lemon: String,
  Bitters: String,
  Black_Pepper: String,
  Black_Rum: String,
  Black_Sambuca: String,
  Blackberries: String,
  Blackberry_Brandy: String,
  Blackberry_Schnapps: String,
  Blackcurrant_Cordial: String,
  Blackcurrant_Schnapps: String,
  Blackcurrant_Squash: String,
  Blended_Whiskey: String,
  Blue_Curacao: String,
  Blue_Maui: String,
  Blueberries: String,
  Blueberry_Schnapps: String,
  Bourbon: String,
  Brandy: String,
  Brown_Sugar: String,
  Butter: String,
  Butterscotch_Schnapps: String,
  Cachaca: String,
  Calvados: String,
  Campari: String,
  Canadian_Whisky: String,
  Candy: String,
  Cantaloupe: String,
  Caramel_Coloring: String,
  Carbonated_Soft_Drink: String,
  Carbonated_Water: String,
  Cardamom: String,
  Cayenne_Pepper: String,
  Celery_Salt: String,
  Celery: String,
  Chambord_Raspberry_Liqueur: String,
  Champagne: String,
  Cherries: String,
  Cherry_Brandy: String,
  Cherry_Cola: String,
  Cherry_Grenadine: String,
  Cherry_Heering: String,
  Cherry_Juice: String,
  Cherry_Liqueur: String,
  Cherry: String,
  Chocolate_Ice_cream: String,
  Chocolate_Liqueur: String,
  Chocolate_Milk: String,
  Chocolate_Syrup: String,
  Chocolate: String,
  Cider: String,
  Cinnamon_Schnapps: String,
  Cinnamon: String,
  Citrus_Vodka: String,
  Clamato_Juice: String,
  Cloves: String,
  Club_Soda: String,
  Coca_Cola: String,
  Cocktail_Onion: String,
  Cocoa_Powder: String,
  Coconut_Cream: String,
  Coconut_Liqueur: String,
  Coconut_Milk: String,
  Coconut_Rum: String,
  Coconut_Syrup: String,
  Coffee_Brandy: String,
  Coffee_Liqueur: String,
  Coffee: String,
  Cognac: String,
  Cointreau: String,
  Cola: String,
  Cold_Water: String,
  Condensed_Milk: String,
  Coriander: String,
  Corn_Syrup: String,
  Cornstarch: String,
  Corona: String,
  Cranberries: String,
  Cranberry_Juice: String,
  Cranberry_Liqueur: String,
  Cranberry_Vodka: String,
  Cream_of_Coconut: String,
  Cream_Sherry: String,
  Cream_Soda: String,
  Cream: String,
  Creme_De_Almond: String,
  Creme_De_Banane: String,
  Creme_De_Cacao: String,
  Creme_De_Cassis: String,
  Creme_De_Noyaux: String,
  Creme_Fraiche: String,
  Crown_Royal: String,
  Crystal_Light: String,
  Cucumber: String,
  Cumin_Powder: String,
  Cumin_Seed: String,
  Curacao: String,
  Cynar: String,
  Daiquiri_Mix: String,
  Dark_Chocolate: String,
  Dark_Creme_De_Cacao: String,
  Dark_Rum: String,
  Dark_Soy_Sauce: String,
  Demerara_Sugar: String,
  Dr_Pepper: String,
  Drambuie: String,
  Dried_Oregano: String,
  Dry_Vermouth: String,
  Dubonnet_Blanc: String,
  Dubonnet_Rouge: String,
  Egg_White: String,
  Egg_Yolk: String,
  Egg: String,
  Eggnog: String,
  Erin_Cream: String,
  Espresso: String,
  Everclear: String,
  Fanta: String,
  Fennel_Seeds: String,
  Firewater: String,
  Flaked_Almonds: String,
  Food_Coloring: String,
  Forbidden_Fruit: String,
  Frangelico: String,
  Fresca: String,
  Fresh_Basil: String,
  Fresh_Lemon_Juice: String,
  Fruit_Juice: String,
  Fruit_Punch: String,
  Fruit: String,
  Galliano: String,
  Garlic_Sauce: String,
  Gatorade: String,
  Ginger_Ale: String,
  Ginger_Beer: String,
  Ginger: String,
  Glycerine: String,
  Godiva_Liqueur: String,
  Gold_rum: String,
  Gold_Tequila: String,
  Goldschlager: String,
  Grain_Alcohol: String,
  Grand_Marnier: String,
  Granulated_Sugar: String,
  Grape_juice: String,
  Grape_soda: String,
  Grapefruit_Juice: String,
  Grapes: String,
  Green_Chartreuse: String,
  Green_Creme_de_Menthe: String,
  Green_Ginger_Wine: String,
  Green_Olives: String,
  Grenadine: String,
  Ground_Ginger: String,
  Guava_juice: String,
  Guinness_stout: String,
  Guinness: String,
  Half_and_half: String,
  Hawaiian_punch: String,
  Hazelnut_liqueur: String,
  Heavy_cream: String,
  Honey: String,
  Hooch: String,
  Hot_Chocolate: String,
  Hot_Damn: String,
  Hot_Sauce: String,
  Hpnotiq: String,
  Ice_Cream: String,
  Ice: String,
  Iced_tea: String,
  Irish_cream: String,
  Irish_Whiskey: String,
  Jack_Daniels: String,
  Jello: String,
  Jelly: String,
  Jagermeister: String,
  Jim_Beam: String,
  Johnnie_Walker: String,
  Kahlua: String,
  Key_Largo_Schnapps: String,
  Kirschwasser: String,
  Kiwi_liqueur: String,
  Kiwi: String,
  Kool_Aid: String,
  Kummel: String,
  Lager: String,
  Lemon_Juice: String,
  Lemon_Peel: String,
  Lemon_soda: String,
  Lemon_vodka: String,
  Lemon_lime_soda: String,
  lemon_lime: String,
  lemon: String,
  Lemonade: String,
  Licorice_Root: String,
  Light_Cream: String,
  Light_Rum: String,
  Lillet: String,
  Lime_juice_cordial: String,
  Lime_Juice: String,
  Lime_liqueur: String,
  Lime_Peel: String,
  Lime_vodka: String,
  Lime: String,
  Limeade: String,
  Madeira: String,
  Malibu_Rum: String,
  Mandarin: String,
  Mandarine_napoleon: String,
  Mango: String,
  Maple_syrup: String,
  Maraschino_cherry_juice: String,
  Maraschino_Cherry: String,
  Maraschino_Liqueur: String,
  Margarita_mix: String,
  Marjoram_leaves: String,
  Marshmallows: String,
  Maui: String,
  Melon_Liqueur: String,
  Melon_Vodka: String,
  Mezcal: String,
  Midori_Melon_Liqueur: String,
  Midori: String,
  Milk: String,
  Mint_syrup: String,
  Mint: String,
  Mountain_Dew: String,
  Nutmeg: String,
  Olive_Oil: String,
  Olive: String,
  Onion: String,
  Orange_Bitters: String,
  Orange_Curacao: String,
  Orange_Juice: String,
  Orange_liqueur: String,
  Orange_Peel: String,
  Orange_rum: String,
  Orange_Soda: String,
  Orange_spiral: String,
  Orange_vodka: String,
  Orange: String,
  Oreo_cookie: String,
  Orgeat_Syrup: String,
  Ouzo: String,
  Oyster_Sauce: String,
  Papaya_juice: String,
  Papaya: String,
  Parfait_amour: String,
  Passion_fruit_juice: String,
  Passion_fruit_syrup: String,
  Passoa: String,
  Peach_brandy: String,
  Peach_juice: String,
  Peach_liqueur: String,
  Peach_Nectar: String,
  Peach_Schnapps: String,
  Peach_Vodka: String,
  Peach: String,
  Peachtree_schnapps: String,
  Peanut_Oil: String,
  Pepper: String,
  Peppermint_extract: String,
  Peppermint_Schnapps: String,
  Pepsi_Cola: String,
  Pernod: String,
  Peychaud_bitters: String,
  Pina_colada_mix: String,
  Pineapple_Juice: String,
  Pineapple_rum: String,
  Pineapple_vodka: String,
  Pineapple_orange_banana_juice: String,
  Pineapple: String,
  Pink_lemonade: String,
  Pisang_Ambon: String,
  Pisco: String,
  Plain_Chocolate: String,
  Plain_Flour: String,
  Plums: String,
  Port: String,
  Powdered_Sugar: String,
  Purple_passion: String,
  Raisins: String,
  Raspberry_cordial: String,
  Raspberry_Jam: String,
  Raspberry_Juice: String,
  Raspberry_Liqueur: String,
  Raspberry_schnapps: String,
  Raspberry_syrup: String,
  Raspberry_Vodka: String,
  Red_Chile_Flakes: String,
  Red_Chili_Flakes: String,
  Red_Hot_Chili_Flakes: String,
  Red_Wine: String,
  Rhubarb: String,
  Ricard: String,
  Rock_Salt: String,
  Root_beer_schnapps: String,
  Root_beer: String,
  Roses_sweetened_lime_juice: String,
  Rosewater: String,
  Rumple_Minze: String,
  Rye_Whiskey: String,
  Sake: String,
  Salt: String,
  Sambuca: String,
  Sarsaparilla: String,
  Schnapps: String,
  Schweppes_Lemon: String,
  Schweppes_Russchian: String,
  Sherbet: String,
  Sherry: String,
  Sirup_of_roses: String,
  Sloe_Gin: String,
  Soda_Water: String,
  Sour_Apple_Pucker: String,
  Sour_Mix: String,
  Southern_Comfort: String,
  Soy_Milk: String,
  Soy_Sauce: String,
  Soya_Milk: String,
  Soya_Sauce: String,
  Spiced_Rum: String,
  Sprite: String,
  Squeezed_Orange: String,
  Squirt: String,
  Strawberries: String,
  Strawberry_juice: String,
  Strawberry_liqueur: String,
  Strawberry_Schnapps: String,
  Strawberry_syrup: String,
  Sugar_Syrup: String,
  Sugar: String,
  Sunny_delight: String,
  Surge: String,
  Swedish_punsch: String,
  Sweet_and_Sour: String,
  Sweet_Cream: String,
  Sweet_Vermouth: String,
  Tabasco_Sauce: String,
  Tang: String,
  Tawny_port: String,
  Tea: String,
  Tennessee_whiskey: String,
  Tequila_rose: String,
  Tia_Maria: String,
  Tomato_Juice: String,
  Tomato: String,
  Tonic_Water: String,
  Triple_Sec: String,
  Tropicana: String,
  Tuaca: String,
  Vanilla_extract: String,
  Vanilla_Ice_Cream: String,
  Vanilla_liqueur: String,
  Vanilla_schnapps: String,
  Vanilla_syrup: String,
  Vanilla_vodka: String,
  Vanilla: String,
  Vermouth: String,
  Vinegar: String,
  Water: String,
  Watermelon_schnapps: String,
  Whipped_Cream: String,
  Whipping_Cream: String,
  White_chocolate_liqueur: String,
  White_Creme_de_Menthe: String,
  White_grape_juice: String,
  White_port: String,
  White_Rum: String,
  White_Vinegar: String,
  White_Wine: String,
  Wild_Turkey: String,
  Wildberry_schnapps: String,
  Wine: String,
  Worcestershire_Sauce: String,
  Wormwood: String,
  Yeast: String,
  Yellow_Chartreuse: String,
  Yoghurt: String,
  Yukon_Jack: String,
  Zima: String,
  Caramel_Sauce: String,
  Chocolate_Sauce: String,
  Lillet_Blanc: String,
  Peach_Bitters: String,
  Mini_snickers_bars: String,
  Prosecco: String,
  Salted_Chocolate: String,
  Martini_Rosso: String,
  Martini_Bianco: String,
  Martini_Extra_Dry: String,
  Fresh_Lime_Juice: String,
  Fresh_Mint: String,
  Rosemary: String,
  Habanero_Peppers: String,
  Ilegal_Joven_mezcal: String,
  Elderflower_cordial: String,
  Rosso_Vermouth: String,
  Creme_de_Violette: String,
  Cocchi_Americano: String,
  White_Vermouth: String,
  Dry_Curacao: String,
  Nocino: String,
  Averna: String,
  Ramazzotti: String,
  Fernet_Branca: String,
  Allspice_Dram: String,
  Falernum: String,
  Singani: String,
  Arrack: String,
  Blackstrap_rum: String,
  Ginger_Syrup: String,
  Honey_syrup: String,
  Blended_Scotch: String,
  Islay_single_malt_Scotch: String,
  One_Fifty_One_proof_rum: String,
  Seven_up: String,
  Absinthe: String,
  Absolut_citron: String,
  Creme_de_Mure: String,
  Olive_Brine: String,
  Pineapple_Syrup: String,
  St_Germain: String,
  Lavender: String,
  Whiskey: String,
  Whisky: String
})
var Ingredient = mongoose.model('Ingredient', ingredientSchema);

var drinkSchema = new mongoose.Schema({
  idDrink: String,
  strDrink: String,
  strDrinkAlternate: String,
  strDrinkES: String,
  strDrinkDE: String,
  strDrinkFR: String,
  'strDrinkZH-HANS': String,
  'strDrinkZH-HANT': String,
  strTags: String,
  strVideo: String,
  strCategory: String,
  strIBA: String,
  strAlcoholic: String,
  strGlass: String,
  strInstructions: String,
  strInstructionsES: String,
  strInstructionsDE: String,
  strInstructionsFR: String,
  'strInstructionsZH-HANS': String,
  'strInstructionsZH-HANT': String,
  strDrinkThumb: String,
  strIngredient1: String,
  strIngredient2: String,
  strIngredient3: String,
  strIngredient4: String,
  strIngredient5: String,
  strIngredient6: String,
  strIngredient7: String,
  strIngredient8: String,
  strIngredient9: String,
  strIngredient10: String,
  strIngredient11: String,
  strIngredient12: String,
  strIngredient13: String,
  strIngredient14: String,
  strIngredient15: String,
  strMeasure1: String,
  strMeasure2: String,
  strMeasure3: String,
  strMeasure4: String,
  strMeasure5: String,
  strMeasure6: String,
  strMeasure7: String,
  strMeasure8: String,
  strMeasure9: String,
  strMeasure10: String,
  strMeasure11: String,
  strMeasure12: String,
  strMeasure13: String,
  strMeasure14: String,
  strMeasure15: String,
  strCreativeCommonsConfirmed: String,
  dateModified: String
});

var Drink = mongoose.model('Drink', drinkSchema);

module.exports = {
  populateArrayWithDrinks: () => {
    for (var i = 0; i < drinks.length; i++) {
      let drinkID = drinks[i].idDrink;

      request(`https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=${drinkID}`, function (error, response, body) {
        // console.error('error:', error); // Print the error if one occurred
        // console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
        // arrayOfDrinks.push(body); // Print the HTML for the Google homepage.

        let json = JSON.parse(body);
        let drinkObj = json.drinks[0]
        var currentDrink = new Drink(drinkObj);

        currentDrink.save(function (err, currentDrink) {
          if (err){
            console.log(err)
          }
          else {
            console.log(`success in logging ${drinkID} to mongo`)
          }
        });
      });
    }
  },
  getAllDrinks: (callback) => {
    Drink.find({}, function (err, docs) {
      if (err) {
        console.log(err)
      } else {
        callback(docs)
      }
    })
  },
  updateIngredients: (data) => {
    var currentIngredients = new Ingredient(data.ingredientData);

    console.log("data in the db", data.ingredientData)

    //NOTE: this might only work if there is a record in the db.  Potential for this to stiop working if the existing data is dropped.
    Ingredient.deleteOne({ }, function (err) {
      if (err) {
        console.log('Delete error: ', err);
      } else {
        currentIngredients.save(function (err, currentDrink) {
          if (err){
            console.log('Add error: ', err)
          }
          else {
            console.log(`success in deleting and adding ingredients to db`)
          }
        })
      }
    });
  },
  getAllIngredients: (callback) => {
    Ingredient.find({}, function (err, docs) {
      if (err) {
        console.log(err)
      } else {
        callback(docs)
      }
    })
  }
  // addFavorite: () => {
  //   // db.collection.update(doc, doc, {upsert:true})
  // }
}


// module.exports.updateIngredients()




// {
//   Vodka: false,
//   Gin: false,
//   Rum: false,
//   Tequila: false,
//   Scotch: false,
//   Absolut_Kurant: false,
//   Absolut_Peppar: false,
//   Absolut_Vodka: false,
//   Advocaat: false,
//   Aejo_Rum: false,
//   Aftershock: false,
//   Agave_Syrup: false,
//   Ale: false,
//   Allspice: false,
//   Almond_Extract: false,
//   Almond_Flavoring: false,
//   Almond: false,
//   Amaretto: false,
//   Angelica_Root: false,
//   Angostura_Bitters: false,
//   Anis: false,
//   Anise: false,
//   Anisette: false,
//   Aperol: false,
//   Apfelkorn: false,
//   Apple_Brandy: false,
//   Apple_Cider: false,
//   Apple_Juice: false,
//   Apple_Schnapps: false,
//   Apple: false,
//   Applejack: false,
//   Apricot_Brandy: false,
//   Apricot_Nectar: false,
//   Apricot: false,
//   Aquavit: false,
//   Asafoetida: false,
//   Añejo_Rum: false,
//   Bacardi_Limon: false,
//   Bacardi: false,
//   Baileys_Irish_Cream: false,
//   Banana_Liqueur: false,
//   Banana_Rum: false,
//   Banana_Syrup: false,
//   Banana: false,
//   Barenjager: false,
//   Basil: false,
//   Beef_Stock: false,
//   Beer: false,
//   Benedictine: false,
//   Berries: false,
//   Bitter_lemon: false,
//   Bitters: false,
//   Black_Pepper: false,
//   Black_Rum: false,
//   Black_Sambuca: false,
//   Blackberries: false,
//   Blackberry_Brandy: false,
//   Blackberry_Schnapps: false,
//   Blackcurrant_Cordial: false,
//   Blackcurrant_Schnapps: false,
//   Blackcurrant_Squash: false,
//   Blended_Whiskey: false,
//   Blue_Curacao: false,
//   Blue_Maui: false,
//   Blueberries: false,
//   Blueberry_Schnapps: false,
//   Bourbon: false,
//   Brandy: false,
//   Brown_Sugar: false,
//   Butter: false,
//   Butterscotch_Schnapps: false,
//   Cachaca: false,
//   Calvados: false,
//   Campari: false,
//   Canadian_Whisky: false,
//   Candy: false,
//   Cantaloupe: false,
//   Caramel_Coloring: false,
//   Carbonated_Soft_Drink: false,
//   Carbonated_Water: false,
//   Cardamom: false,
//   Cayenne_Pepper: false,
//   Celery_Salt: false,
//   Celery: false,
//   Chambord_Raspberry_Liqueur: false,
//   Champagne: false,
//   Cherries: false,
//   Cherry_Brandy: false,
//   Cherry_Cola: false,
//   Cherry_Grenadine: false,
//   Cherry_Heering: false,
//   Cherry_Juice: false,
//   Cherry_Liqueur: false,
//   Cherry: false,
//   Chocolate_Ice_cream: false,   //Chocolate_Ice-cream
//   Chocolate_Liqueur: false,
//   Chocolate_Milk: false,
//   Chocolate_Syrup: false,
//   Chocolate: false,
//   Cider: false,
//   Cinnamon_Schnapps: false,
//   Cinnamon: false,
//   Citrus_Vodka: false,
//   Clamato_Juice: false,
//   Cloves: false,
//   Club_Soda: false,
//   Coca_Cola: false,  //Coca-Cola
//   Cocktail_Onion: false,
//   Cocoa_Powder: false,
//   Coconut_Cream: false,
//   Coconut_Liqueur: false,
//   Coconut_Milk: false,
//   Coconut_Rum: false,
//   Coconut_Syrup: false,
//   Coffee_Brandy: false,
//   Coffee_Liqueur: false,
//   Coffee: false,
//   Cognac: false,
//   Cointreau: false,
//   Cola: false,
//   Cold_Water: false,
//   Condensed_Milk: false,
//   Coriander: false,
//   Corn_Syrup: false,
//   Cornstarch: false,
//   Corona: false,
//   Cranberries: false,
//   Cranberry_Juice: false,
//   Cranberry_Liqueur: false,
//   Cranberry_Vodka: false,
//   Cream_of_Coconut: false,
//   Cream_Sherry: false,
//   Cream_Soda: false,
//   Cream: false,
//   Creme_De_Almond: false,
//   Creme_De_Banane: false,
//   Creme_De_Cacao: false,
//   Creme_De_Cassis: false,
//   Creme_De_Noyaux: false,
//   Creme_Fraiche: false,
//   Crown_Royal: false,
//   Crystal_Light: false,
//   Cucumber: false,
//   Cumin_Powder: false,
//   Cumin_Seed: false,
//   Curacao: false,
//   Cynar: false,
//   Daiquiri_Mix: false,
//   Dark_Chocolate: false,
//   Dark_Creme_De_Cacao: false,
//   Dark_Rum: false,
//   Dark_Soy_Sauce: false,
//   Demerara_Sugar: false,
//   Dr_Pepper: false,  //Dr._Pepper
//   Drambuie: false,
//   Dried_Oregano: false,
//   Dry_Vermouth: false,
//   Dubonnet_Blanc: false,
//   Dubonnet_Rouge: false,
//   Egg_White: false,
//   Egg_Yolk: false,
//   Egg: false,
//   Eggnog: false,
//   Erin_Cream: false,
//   Espresso: false,
//   Everclear: false,
//   Fanta: false,
//   Fennel_Seeds: false,
//   Firewater: false,
//   Flaked_Almonds: false,
//   Food_Coloring: false,
//   Forbidden_Fruit: false,
//   Frangelico: false,
//   Fresca: false,
//   Fresh_Basil: false,
//   Fresh_Lemon_Juice: false,
//   Fruit_Juice: false,
//   Fruit_Punch: false,
//   Fruit: false,
//   Galliano: false,
//   Garlic_Sauce: false,
//   Gatorade: false,
//   Ginger_Ale: false,
//   Ginger_Beer: false,
//   Ginger: false,
//   Glycerine: false,
//   Godiva_Liqueur: false,
//   Gold_rum: false,
//   Gold_Tequila: false,
//   Goldschlager: false,
//   Grain_Alcohol: false,
//   Grand_Marnier: false,
//   Granulated_Sugar: false,
//   Grape_juice: false,
//   Grape_soda: false,
//   Grapefruit_Juice: false,
//   Grapes: false,
//   Green_Chartreuse: false,
//   Green_Creme_de_Menthe: false,
//   Green_Ginger_Wine: false,
//   Green_Olives: false,
//   Grenadine: false,
//   Ground_Ginger: false,
//   Guava_juice: false,
//   Guinness_stout: false,
//   Guinness: false,
//   Half_and_half: false,  //Half-and-half
//   Hawaiian_punch: false,
//   Hazelnut_liqueur: false,
//   Heavy_cream: false,
//   Honey: false,
//   Hooch: false,
//   Hot_Chocolate: false,
//   Hot_Damn: false,
//   Hot_Sauce: false,
//   Hpnotiq: false,
//   Ice_Cream: false,  //Ice-Cream
//   Ice: false,
//   Iced_tea: false,
//   Irish_cream: false,
//   Irish_Whiskey: false,
//   Jack_Daniels: false,
//   Jello: false,
//   Jelly: false,
//   Jagermeister: false,
//   Jim_Beam: false,
//   Johnnie_Walker: false,
//   Kahlua: false,
//   Key_Largo_Schnapps: false,
//   Kirschwasser: false,
//   Kiwi_liqueur: false,
//   Kiwi: false,
//   Kool_Aid: false,  //Kool-Aid
//   Kummel: false,
//   Lager: false,
//   Lemon_Juice: false,
//   Lemon_Peel: false,
//   Lemon_soda: false,
//   Lemon_vodka: false,
//   Lemon_lime_soda: false,  //Lemon-lime_soda
//   lemon_lime: false,    //lemon-lime
//   lemon: false,
//   Lemonade: false,
//   Licorice_Root: false,
//   Light_Cream: false,
//   Light_Rum: false,
//   Lillet: false,
//   Lime_juice_cordial: false,
//   Lime_Juice: false,
//   Lime_liqueur: false,
//   Lime_Peel: false,
//   Lime_vodka: false,
//   Lime: false,
//   Limeade: false,
//   Madeira: false,
//   Malibu_Rum: false,
//   Mandarin: false,
//   Mandarine_napoleon: false,
//   Mango: false,
//   Maple_syrup: false,
//   Maraschino_cherry_juice: false,
//   Maraschino_Cherry: false,
//   Maraschino_Liqueur: false,
//   Margarita_mix: false,
//   Marjoram_leaves: false,
//   Marshmallows: false,
//   Maui: false,
//   Melon_Liqueur: false,
//   Melon_Vodka: false,
//   Mezcal: false,
//   Midori_Melon_Liqueur: false,
//   Midori: false,
//   Milk: false,
//   Mint_syrup: false,
//   Mint: false,
//   Mountain_Dew: false,
//   Nutmeg: false,
//   Olive_Oil: false,
//   Olive: false,
//   Onion: false,
//   Orange_Bitters: false,
//   Orange_Curacao: false,
//   Orange_Juice: false,
//   Orange_liqueur: false,
//   Orange_Peel: false,
//   Orange_rum: false,
//   Orange_Soda: false,
//   Orange_spiral: false,
//   Orange_vodka: false,
//   Orange: false,
//   Oreo_cookie: false,
//   Orgeat_Syrup: false,
//   Ouzo: false,
//   Oyster_Sauce: false,
//   Papaya_juice: false,
//   Papaya: false,
//   Parfait_amour: false,
//   Passion_fruit_juice: false,
//   Passion_fruit_syrup: false,
//   Passoa: false,
//   Peach_brandy: false,
//   Peach_juice: false,
//   Peach_liqueur: false,
//   Peach_Nectar: false,
//   Peach_Schnapps: false,
//   Peach_Vodka: false,
//   Peach: false,
//   Peachtree_schnapps: false,
//   Peanut_Oil: false,
//   Pepper: false,
//   Peppermint_extract: false,
//   Peppermint_Schnapps: false,
//   Pepsi_Cola: false,
//   Pernod: false,
//   Peychaud_bitters: false,
//   Pina_colada_mix: false,
//   Pineapple_Juice: false,
//   Pineapple_rum: false,
//   Pineapple_vodka: false,
//   Pineapple_orange_banana_juice: false,   //Pineapple-orange-banana_juice
//   Pineapple: false,
//   Pink_lemonade: false,
//   Pisang_Ambon: false,
//   Pisco: false,
//   Plain_Chocolate: false,
//   Plain_Flour: false,
//   Plums: false,
//   Port: false,
//   Powdered_Sugar: false,
//   Purple_passion: false,
//   Raisins: false,
//   Raspberry_cordial: false,
//   Raspberry_Jam: false,
//   Raspberry_Juice: false,
//   Raspberry_Liqueur: false,
//   Raspberry_schnapps: false,
//   Raspberry_syrup: false,
//   Raspberry_Vodka: false,
//   Red_Chile_Flakes: false,
//   Red_Chili_Flakes: false,
//   Red_Hot_Chili_Flakes: false,
//   Red_Wine: false,
//   Rhubarb: false,
//   Ricard: false,
//   Rock_Salt: false,
//   Root_beer_schnapps: false,
//   Root_beer: false,
//   Roses_sweetened_lime_juice: false,
//   Rosewater: false,
//   Rumple_Minze: false,
//   Rye_Whiskey: false,
//   Sake: false,
//   Salt: false,
//   Sambuca: false,
//   Sarsaparilla: false,
//   Schnapps: false,
//   Schweppes_Lemon: false,
//   Schweppes_Russchian: false,
//   Sherbet: false,
//   Sherry: false,
//   Sirup_of_roses: false,
//   Sloe_Gin: false,
//   Soda_Water: false,
//   Sour_Apple_Pucker: false,
//   Sour_Mix: false,
//   Southern_Comfort: false,
//   Soy_Milk: false,
//   Soy_Sauce: false,
//   Soya_Milk: false,
//   Soya_Sauce: false,
//   Spiced_Rum: false,
//   Sprite: false,
//   Squeezed_Orange: false,
//   Squirt: false,
//   Strawberries: false,
//   Strawberry_juice: false,
//   Strawberry_liqueur: false,
//   Strawberry_Schnapps: false,
//   Strawberry_syrup: false,
//   Sugar_Syrup: false,
//   Sugar: false,
//   Sunny_delight: false,
//   Surge: false,
//   Swedish_punsch: false,
//   Sweet_and_Sour: false,
//   Sweet_Cream: false,
//   Sweet_Vermouth: false,
//   Tabasco_Sauce: false,
//   Tang: false,
//   Tawny_port: false,
//   Tea: false,
//   Tennessee_whiskey: false,
//   Tequila_rose: false,
//   Tia_Maria: false,
//   Tomato_Juice: false,
//   Tomato: false,
//   Tonic_Water: false,
//   Triple_Sec: false,
//   Tropicana: false,
//   Tuaca: false,
//   Vanilla_extract: false,
//   Vanilla_Ice_Cream: false,   //Vanilla_Ice-Cream
//   Vanilla_liqueur: false,
//   Vanilla_schnapps: false,
//   Vanilla_syrup: false,
//   Vanilla_vodka: false,
//   Vanilla: false,
//   Vermouth: false,
//   Vinegar: false,
//   Water: false,
//   Watermelon_schnapps: false,
//   Whipped_Cream: false,
//   Whipping_Cream: false,
//   White_chocolate_liqueur: false,
//   White_Creme_de_Menthe: false,
//   White_grape_juice: false,
//   White_port: false,
//   White_Rum: false,
//   White_Vinegar: false,
//   White_Wine: false,
//   Wild_Turkey: false,
//   Wildberry_schnapps: false,
//   Wine: false,
//   Worcestershire_Sauce: false,
//   Wormwood: false,
//   Yeast: false,
//   Yellow_Chartreuse: false,
//   Yoghurt: false,
//   Yukon_Jack: false,
//   Zima: false,
//   Caramel_Sauce: false,
//   Chocolate_Sauce: false,
//   Lillet_Blanc: false,
//   Peach_Bitters: false,
//   Mini_snickers_bars: false,   //Mini-snickers_bars
//   Prosecco: false,
//   Salted_Chocolate: false,
//   Martini_Rosso: false,
//   Martini_Bianco: false,
//   Martini_Extra_Dry: false,
//   Fresh_Lime_Juice: false,
//   Fresh_Mint: false,
//   Rosemary: false,
//   Habanero_Peppers: false,
//   Ilegal_Joven_mezcal: false,
//   Elderflower_cordial: false,
//   Rosso_Vermouth: false,
//   Creme_de_Violette: false,
//   Cocchi_Americano: false,
//   White_Vermouth: false,
//   Dry_Curacao: false,
//   Nocino: false,
//   Averna: false,
//   Ramazzotti: false,
//   Fernet_Branca: false,   //Fernet-Branca
//   Allspice_Dram: false,
//   Falernum: false,
//   Singani: false,
//   Arrack: false,
//   Blackstrap_rum: false,
//   Ginger_Syrup: false,
//   Honey_syrup: false,
//   Blended_Scotch: false,
//   Islay_single_malt_Scotch: false,
//   One_Fifty_One_proof_rum: false,    //151_proof_rum
//   Seven_up: false,   ///7-up
//   Absinthe: false,
//   Absolut_citron: false,
//   Creme_de_Mure: false,
//   Olive_Brine: false,
//   Pineapple_Syrup: false,
//   St_Germain: false,    //St._Germain
//   Lavender: false,
//   Whiskey: false,
//   Whisky: false
// }


