import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import IngredientSelector from './IngredientSelector.jsx';
import DrinkList from './DrinkList.jsx';
import Drink from './Drink.jsx';
import axios from 'axios';

// const incredients = require('../../../database/allIngredients')

class Landing extends Component {
  constructor(props) {
    super(props);

    this.state = {
      Vodka: false,
      Gin: false,
      Rum: false,
      Tequila: false,
      Scotch: false,
      Absolut_Kurant: false,
      Absolut_Peppar: false,
      Absolut_Vodka: false,
      Advocaat: false,
      Aejo_Rum: false,
      Aftershock: false,
      Agave_Syrup: false,
      Ale: false,
      Allspice: false,
      Almond_Extract: false,
      Almond_Flavoring: false,
      Almond: false,
      Amaretto: false,
      Angelica_Root: false,
      Angostura_Bitters: false,
      Anis: false,
      Anise: false,
      Anisette: false,
      Aperol: false,
      Apfelkorn: false,
      Apple_Brandy: false,
      Apple_Cider: false,
      Apple_Juice: false,
      Apple_Schnapps: false,
      Apple: false,
      Applejack: false,
      Apricot_Brandy: false,
      Apricot_Nectar: false,
      Apricot: false,
      Aquavit: false,
      Asafoetida: false,
      Añejo_Rum: false,
      Bacardi_Limon: false,
      Bacardi: false,
      Baileys_Irish_Cream: false,
      Banana_Liqueur: false,
      Banana_Rum: false,
      Banana_Syrup: false,
      Banana: false,
      Barenjager: false,
      Basil: false,
      Beef_Stock: false,
      Beer: false,
      Benedictine: false,
      Berries: false,
      Bitter_lemon: false,
      Bitters: false,
      Black_Pepper: false,
      Black_Rum: false,
      Black_Sambuca: false,
      Blackberries: false,
      Blackberry_Brandy: false,
      Blackberry_Schnapps: false,
      Blackcurrant_Cordial: false,
      Blackcurrant_Schnapps: false,
      Blackcurrant_Squash: false,
      Blended_Whiskey: false,
      Blue_Curacao: false,
      Blue_Maui: false,
      Blueberries: false,
      Blueberry_Schnapps: false,
      Bourbon: false,
      Brandy: false,
      Brown_Sugar: false,
      Butter: false,
      Butterscotch_Schnapps: false,
      Cachaca: false,
      Calvados: false,
      Campari: false,
      Canadian_Whisky: false,
      Candy: false,
      Cantaloupe: false,
      Caramel_Coloring: false,
      Carbonated_Soft_Drink: false,
      Carbonated_Water: false,
      Cardamom: false,
      Cayenne_Pepper: false,
      Celery_Salt: false,
      Celery: false,
      Chambord_Raspberry_Liqueur: false,
      Champagne: false,
      Cherries: false,
      Cherry_Brandy: false,
      Cherry_Cola: false,
      Cherry_Grenadine: false,
      Cherry_Heering: false,
      Cherry_Juice: false,
      Cherry_Liqueur: false,
      Cherry: false,
      Chocolate_Ice_cream: false,   //Chocolate_Ice-cream
      Chocolate_Liqueur: false,
      Chocolate_Milk: false,
      Chocolate_Syrup: false,
      Chocolate: false,
      Cider: false,
      Cinnamon_Schnapps: false,
      Cinnamon: false,
      Citrus_Vodka: false,
      Clamato_Juice: false,
      Cloves: false,
      Club_Soda: false,
      Coca_Cola: false,  //Coca-Cola
      Cocktail_Onion: false,
      Cocoa_Powder: false,
      Coconut_Cream: false,
      Coconut_Liqueur: false,
      Coconut_Milk: false,
      Coconut_Rum: false,
      Coconut_Syrup: false,
      Coffee_Brandy: false,
      Coffee_Liqueur: false,
      Coffee: false,
      Cognac: false,
      Cointreau: false,
      Cola: false,
      Cold_Water: false,
      Condensed_Milk: false,
      Coriander: false,
      Corn_Syrup: false,
      Cornstarch: false,
      Corona: false,
      Cranberries: false,
      Cranberry_Juice: false,
      Cranberry_Liqueur: false,
      Cranberry_Vodka: false,
      Cream_of_Coconut: false,
      Cream_Sherry: false,
      Cream_Soda: false,
      Cream: false,
      Creme_De_Almond: false,
      Creme_De_Banane: false,
      Creme_De_Cacao: false,
      Creme_De_Cassis: false,
      Creme_De_Noyaux: false,
      Creme_Fraiche: false,
      Crown_Royal: false,
      Crystal_Light: false,
      Cucumber: false,
      Cumin_Powder: false,
      Cumin_Seed: false,
      Curacao: false,
      Cynar: false,
      Daiquiri_Mix: false,
      Dark_Chocolate: false,
      Dark_Creme_De_Cacao: false,
      Dark_Rum: false,
      Dark_Soy_Sauce: false,
      Demerara_Sugar: false,
      Dr_Pepper: false,  //Dr._Pepper
      Drambuie: false,
      Dried_Oregano: false,
      Dry_Vermouth: false,
      Dubonnet_Blanc: false,
      Dubonnet_Rouge: false,
      Egg_White: false,
      Egg_Yolk: false,
      Egg: false,
      Eggnog: false,
      Erin_Cream: false,
      Espresso: false,
      Everclear: false,
      Fanta: false,
      Fennel_Seeds: false,
      Firewater: false,
      Flaked_Almonds: false,
      Food_Coloring: false,
      Forbidden_Fruit: false,
      Frangelico: false,
      Fresca: false,
      Fresh_Basil: false,
      Fresh_Lemon_Juice: false,
      Fruit_Juice: false,
      Fruit_Punch: false,
      Fruit: false,
      Galliano: false,
      Garlic_Sauce: false,
      Gatorade: false,
      Ginger_Ale: false,
      Ginger_Beer: false,
      Ginger: false,
      Glycerine: false,
      Godiva_Liqueur: false,
      Gold_rum: false,
      Gold_Tequila: false,
      Goldschlager: false,
      Grain_Alcohol: false,
      Grand_Marnier: false,
      Granulated_Sugar: false,
      Grape_juice: false,
      Grape_soda: false,
      Grapefruit_Juice: false,
      Grapes: false,
      Green_Chartreuse: false,
      Green_Creme_de_Menthe: false,
      Green_Ginger_Wine: false,
      Green_Olives: false,
      Grenadine: false,
      Ground_Ginger: false,
      Guava_juice: false,
      Guinness_stout: false,
      Guinness: false,
      Half_and_half: false,  //Half-and-half
      Hawaiian_punch: false,
      Hazelnut_liqueur: false,
      Heavy_cream: false,
      Honey: false,
      Hooch: false,
      Hot_Chocolate: false,
      Hot_Damn: false,
      Hot_Sauce: false,
      Hpnotiq: false,
      Ice_Cream: false,  //Ice-Cream
      Ice: false,
      Iced_tea: false,
      Irish_cream: false,
      Irish_Whiskey: false,
      Jack_Daniels: false,
      Jello: false,
      Jelly: false,
      Jagermeister: false,
      Jim_Beam: false,
      Johnnie_Walker: false,
      Kahlua: false,
      Key_Largo_Schnapps: false,
      Kirschwasser: false,
      Kiwi_liqueur: false,
      Kiwi: false,
      Kool_Aid: false,  //Kool-Aid
      Kummel: false,
      Lager: false,
      Lemon_Juice: false,
      Lemon_Peel: false,
      Lemon_soda: false,
      Lemon_vodka: false,
      Lemon_lime_soda: false,  //Lemon-lime_soda
      lemon_lime: false,    //lemon-lime
      lemon: false,
      Lemonade: false,
      Licorice_Root: false,
      Light_Cream: false,
      Light_Rum: false,
      Lillet: false,
      Lime_juice_cordial: false,
      Lime_Juice: false,
      Lime_liqueur: false,
      Lime_Peel: false,
      Lime_vodka: false,
      Lime: false,
      Limeade: false,
      Madeira: false,
      Malibu_Rum: false,
      Mandarin: false,
      Mandarine_napoleon: false,
      Mango: false,
      Maple_syrup: false,
      Maraschino_cherry_juice: false,
      Maraschino_Cherry: false,
      Maraschino_Liqueur: false,
      Margarita_mix: false,
      Marjoram_leaves: false,
      Marshmallows: false,
      Maui: false,
      Melon_Liqueur: false,
      Melon_Vodka: false,
      Mezcal: false,
      Midori_Melon_Liqueur: false,
      Midori: false,
      Milk: false,
      Mint_syrup: false,
      Mint: false,
      Mountain_Dew: false,
      Nutmeg: false,
      Olive_Oil: false,
      Olive: false,
      Onion: false,
      Orange_Bitters: false,
      Orange_Curacao: false,
      Orange_Juice: false,
      Orange_liqueur: false,
      Orange_Peel: false,
      Orange_rum: false,
      Orange_Soda: false,
      Orange_spiral: false,
      Orange_vodka: false,
      Orange: false,
      Oreo_cookie: false,
      Orgeat_Syrup: false,
      Ouzo: false,
      Oyster_Sauce: false,
      Papaya_juice: false,
      Papaya: false,
      Parfait_amour: false,
      Passion_fruit_juice: false,
      Passion_fruit_syrup: false,
      Passoa: false,
      Peach_brandy: false,
      Peach_juice: false,
      Peach_liqueur: false,
      Peach_Nectar: false,
      Peach_Schnapps: false,
      Peach_Vodka: false,
      Peach: false,
      Peachtree_schnapps: false,
      Peanut_Oil: false,
      Pepper: false,
      Peppermint_extract: false,
      Peppermint_Schnapps: false,
      Pepsi_Cola: false,
      Pernod: false,
      Peychaud_bitters: false,
      Pina_colada_mix: false,
      Pineapple_Juice: false,
      Pineapple_rum: false,
      Pineapple_vodka: false,
      Pineapple_orange_banana_juice: false,   //Pineapple-orange-banana_juice
      Pineapple: false,
      Pink_lemonade: false,
      Pisang_Ambon: false,
      Pisco: false,
      Plain_Chocolate: false,
      Plain_Flour: false,
      Plums: false,
      Port: false,
      Powdered_Sugar: false,
      Purple_passion: false,
      Raisins: false,
      Raspberry_cordial: false,
      Raspberry_Jam: false,
      Raspberry_Juice: false,
      Raspberry_Liqueur: false,
      Raspberry_schnapps: false,
      Raspberry_syrup: false,
      Raspberry_Vodka: false,
      Red_Chile_Flakes: false,
      Red_Chili_Flakes: false,
      Red_Hot_Chili_Flakes: false,
      Red_Wine: false,
      Rhubarb: false,
      Ricard: false,
      Rock_Salt: false,
      Root_beer_schnapps: false,
      Root_beer: false,
      Roses_sweetened_lime_juice: false,
      Rosewater: false,
      Rumple_Minze: false,
      Rye_Whiskey: false,
      Sake: false,
      Salt: false,
      Sambuca: false,
      Sarsaparilla: false,
      Schnapps: false,
      Schweppes_Lemon: false,
      Schweppes_Russchian: false,
      Sherbet: false,
      Sherry: false,
      Sirup_of_roses: false,
      Sloe_Gin: false,
      Soda_Water: false,
      Sour_Apple_Pucker: false,
      Sour_Mix: false,
      Southern_Comfort: false,
      Soy_Milk: false,
      Soy_Sauce: false,
      Soya_Milk: false,
      Soya_Sauce: false,
      Spiced_Rum: false,
      Sprite: false,
      Squeezed_Orange: false,
      Squirt: false,
      Strawberries: false,
      Strawberry_juice: false,
      Strawberry_liqueur: false,
      Strawberry_Schnapps: false,
      Strawberry_syrup: false,
      Sugar_Syrup: false,
      Sugar: false,
      Sunny_delight: false,
      Surge: false,
      Swedish_punsch: false,
      Sweet_and_Sour: false,
      Sweet_Cream: false,
      Sweet_Vermouth: false,
      Tabasco_Sauce: false,
      Tang: false,
      Tawny_port: false,
      Tea: false,
      Tennessee_whiskey: false,
      Tequila_rose: false,
      Tia_Maria: false,
      Tomato_Juice: false,
      Tomato: false,
      Tonic_Water: false,
      Triple_Sec: false,
      Tropicana: false,
      Tuaca: false,
      Vanilla_extract: false,
      Vanilla_Ice_Cream: false,   //Vanilla_Ice-Cream
      Vanilla_liqueur: false,
      Vanilla_schnapps: false,
      Vanilla_syrup: false,
      Vanilla_vodka: false,
      Vanilla: false,
      Vermouth: false,
      Vinegar: false,
      Water: false,
      Watermelon_schnapps: false,
      Whipped_Cream: false,
      Whipping_Cream: false,
      White_chocolate_liqueur: false,
      White_Creme_de_Menthe: false,
      White_grape_juice: false,
      White_port: false,
      White_Rum: false,
      White_Vinegar: false,
      White_Wine: false,
      Wild_Turkey: false,
      Wildberry_schnapps: false,
      Wine: false,
      Worcestershire_Sauce: false,
      Wormwood: false,
      Yeast: false,
      Yellow_Chartreuse: false,
      Yoghurt: false,
      Yukon_Jack: false,
      Zima: false,
      Caramel_Sauce: false,
      Chocolate_Sauce: false,
      Lillet_Blanc: false,
      Peach_Bitters: false,
      Mini_snickers_bars: false,   //Mini-snickers_bars
      Prosecco: false,
      Salted_Chocolate: false,
      Martini_Rosso: false,
      Martini_Bianco: false,
      Martini_Extra_Dry: false,
      Fresh_Lime_Juice: false,
      Fresh_Mint: false,
      Rosemary: false,
      Habanero_Peppers: false,
      Ilegal_Joven_mezcal: false,
      Elderflower_cordial: false,
      Rosso_Vermouth: false,
      Creme_de_Violette: false,
      Cocchi_Americano: false,
      White_Vermouth: false,
      Dry_Curacao: false,
      Nocino: false,
      Averna: false,
      Ramazzotti: false,
      Fernet_Branca: false,   //Fernet-Branca
      Allspice_Dram: false,
      Falernum: false,
      Singani: false,
      Arrack: false,
      Blackstrap_rum: false,
      Ginger_Syrup: false,
      Honey_syrup: false,
      Blended_Scotch: false,
      Islay_single_malt_Scotch: false,
      One_Fifty_One_proof_rum: false,    //151_proof_rum
      Seven_up: false,   ///7-up
      Absinthe: false,
      Absolut_citron: false,
      Creme_de_Mure: false,
      Olive_Brine: false,
      Pineapple_Syrup: false,
      St_Germain: false,    //St._Germain
      Lavender: false,
      Whiskey: false,
      Whisky: false,
      filterDrinks: '',
      Page: 'Landing'
    };

    this.addItemToBar = this.addItemToBar.bind(this);
    this.handleFilterChange = this.handleFilterChange.bind(this);
    this.renderDrinkList = this.renderDrinkList.bind(this);
    this.renderLanding = this.renderLanding.bind(this);
    this.saveIngredients = this.saveIngredients.bind(this);
    this.componentDidMount = this.componentDidMount.bind(this);


  }

  componentDidMount(){
    axios.get('/ingredients')
    .then(response => {
      // handle success


      // let ingredientsFromDB = {};

      let objectToSetState = {
        Absinthe: JSON.parse(response.data[0].Absinthe),
        Absolut_Kurant: JSON.parse(response.data[0].Absolut_Kurant),
        Absolut_Peppar: JSON.parse(response.data[0].Absolut_Peppar),
        Absolut_Vodka: JSON.parse(response.data[0].Absolut_Vodka),
        Absolut_citron: JSON.parse(response.data[0].Absolut_citron),
        Advocaat: JSON.parse(response.data[0].Advocaat)
      }

      // for (var property in response.data[0]) {
      //   // console.log(`key= ${property} value = ${response.data[0][property]}`)
      //   ingredientsFromDB[property] = JSON.parse(response.data[0][property])
      // }

      // console.log(ingredientsFromDB)
      this.setState(objectToSetState)


      // for (let [key, value] of Object.entries(response.data[0])) {
      //   // console.log(`${key}: ${value}`);
        // let tempProp = JSON.parse(response.data[0][key]);
      //   console.log(tempProp)
      //   // ingredientsFromDB[key] = (tempProp)
      //   // ${key}:
      // }

      // console.log(ingredientsFromDB)



    })
    .catch(error => {
      // handle error
      console.log(error);
    })
    .finally(() => {
      // always executed
    });

  }

  addItemToBar(event){
    // console.log('ingredient is here: ', ingredient);
    this.setState({
      [event.target.id]: !this.state[event.target.id]
    });
    // console.log(`The state of ${event.target.id} is ${this.state[event.target.id]}`)
  }

  renderDrinkList(){
    this.setState({
      Page: 'DrinkList'
    })
  }

  renderLanding(){
    this.setState({
      Page: 'Landing',
      filterDrinks: ''
    })
  }

  handleFilterChange(event){
    this.setState({
      filterDrinks: event.target.value
    })
    // this.props.onChange(event.target.value)
  }

  saveIngredients(){
    // console.log('saving your ingredients to db');
    axios.post('/ingredients', {
      ingredientData: this.state
    })
    .then(function (response) {
      // console.log(response);
    })
    .catch(function (error) {
      // console.log(error);
    });

  }

  render() {
    if (this.state.Page === 'Landing') {
      return (
        <div>
          <h1>
            Welcome to Open Bar
          </h1>
          <IngredientSelector
            addItemToBar={this.addItemToBar}
            ingredients={this.state}
            handleFilterChange={this.handleFilterChange}
            renderDrinkList={this.renderDrinkList}
            saveIngredients={this.saveIngredients}/>
        </div>
      )
    } else if (this.state.Page === 'DrinkList') {
      return (
        <div>
          <h1>
            Welcome to Open Bar
          </h1>
          <DrinkList renderLanding={this.renderLanding} />
        </div>
      )
    }
  }
}












export default Landing;


// Vodka: JSON.parse(response.data[0].Vodka),


      this.setState({
        Vodka: JSON.parse(response.data[0].Vodka),
        Gin: JSON.parse(response.data[0].Vodka),
        Rum: JSON.parse(response.data[0].Vodka),
        Tequila: JSON.parse(response.data[0].Vodka),
        Scotch: JSON.parse(response.data[0].Vodka),
        Absolut_Kurant: JSON.parse(response.data[0].Vodka),
        Absolut_Peppar: JSON.parse(response.data[0].Vodka),
        Absolut_Vodka: JSON.parse(response.data[0].Vodka),
        Advocaat: JSON.parse(response.data[0].Vodka),
        Aejo_Rum: JSON.parse(response.data[0].Vodka),
        Aftershock: JSON.parse(response.data[0].Vodka),
        Agave_Syrup: JSON.parse(response.data[0].Vodka),
        Ale: JSON.parse(response.data[0].Vodka),
        Allspice: JSON.parse(response.data[0].Vodka),
        Almond_Extract: JSON.parse(response.data[0].Vodka),
        Almond_Flavoring: JSON.parse(response.data[0].Vodka),
        Almond: JSON.parse(response.data[0].Vodka),
        Amaretto: JSON.parse(response.data[0].Vodka),
        Angelica_Root: JSON.parse(response.data[0].Vodka),
        Angostura_Bitters: JSON.parse(response.data[0].Vodka),
        Anis: JSON.parse(response.data[0].Vodka),
        Anise: JSON.parse(response.data[0].Vodka),
        Anisette: JSON.parse(response.data[0].Vodka),
        Aperol: JSON.parse(response.data[0].Vodka),
        Apfelkorn: JSON.parse(response.data[0].Vodka),
        Apple_Brandy: JSON.parse(response.data[0].Vodka),
        Apple_Cider: JSON.parse(response.data[0].Vodka),
        Apple_Juice: JSON.parse(response.data[0].Vodka),
        Apple_Schnapps: JSON.parse(response.data[0].Vodka),
        Apple: JSON.parse(response.data[0].Vodka),
        Applejack: JSON.parse(response.data[0].Vodka),
        Apricot_Brandy: JSON.parse(response.data[0].Vodka),
        Apricot_Nectar: JSON.parse(response.data[0].Vodka),
        Apricot: JSON.parse(response.data[0].Vodka),
        Aquavit: JSON.parse(response.data[0].Vodka),
        Asafoetida: JSON.parse(response.data[0].Vodka),
        Añejo_Rum: JSON.parse(response.data[0].Vodka),
        Bacardi_Limon: JSON.parse(response.data[0].Vodka),
        Bacardi: JSON.parse(response.data[0].Vodka),
        Baileys_Irish_Cream: JSON.parse(response.data[0].Vodka),
        Banana_Liqueur: JSON.parse(response.data[0].Vodka),
        Banana_Rum: JSON.parse(response.data[0].Vodka),
        Banana_Syrup: JSON.parse(response.data[0].Vodka),
        Banana: JSON.parse(response.data[0].Vodka),
        Barenjager: JSON.parse(response.data[0].Vodka),
        Basil: JSON.parse(response.data[0].Vodka),
        Beef_Stock: JSON.parse(response.data[0].Vodka),
        Beer: JSON.parse(response.data[0].Vodka),
        Benedictine: JSON.parse(response.data[0].Vodka),
        Berries: JSON.parse(response.data[0].Vodka),
        Bitter_lemon: JSON.parse(response.data[0].Vodka),
        Bitters: JSON.parse(response.data[0].Vodka),
        Black_Pepper: JSON.parse(response.data[0].Vodka),
        Black_Rum: JSON.parse(response.data[0].Vodka),
        Black_Sambuca: JSON.parse(response.data[0].Vodka),
        Blackberries: JSON.parse(response.data[0].Vodka),
        Blackberry_Brandy: JSON.parse(response.data[0].Vodka),
        Blackberry_Schnapps: JSON.parse(response.data[0].Vodka),
        Blackcurrant_Cordial: JSON.parse(response.data[0].Vodka),
        Blackcurrant_Schnapps: JSON.parse(response.data[0].Vodka),
        Blackcurrant_Squash: JSON.parse(response.data[0].Vodka),
        Blended_Whiskey: JSON.parse(response.data[0].Vodka),
        Blue_Curacao: JSON.parse(response.data[0].Vodka),
        Blue_Maui: JSON.parse(response.data[0].Vodka),
        Blueberries: JSON.parse(response.data[0].Vodka),
        Blueberry_Schnapps: JSON.parse(response.data[0].Vodka),
        Bourbon: JSON.parse(response.data[0].Vodka),
        Brandy: JSON.parse(response.data[0].Vodka),
        Brown_Sugar: JSON.parse(response.data[0].Vodka),
        Butter: JSON.parse(response.data[0].Vodka),
        Butterscotch_Schnapps: JSON.parse(response.data[0].Vodka),
        Cachaca: JSON.parse(response.data[0].Vodka),
        Calvados: JSON.parse(response.data[0].Vodka),
        Campari: JSON.parse(response.data[0].Vodka),
        Canadian_Whisky: JSON.parse(response.data[0].Vodka),
        Candy: JSON.parse(response.data[0].Vodka),
        Cantaloupe: JSON.parse(response.data[0].Vodka),
        Caramel_Coloring: JSON.parse(response.data[0].Vodka),
        Carbonated_Soft_Drink: JSON.parse(response.data[0].Vodka),
        Carbonated_Water: JSON.parse(response.data[0].Vodka),
        Cardamom: JSON.parse(response.data[0].Vodka),
        Cayenne_Pepper: JSON.parse(response.data[0].Vodka),
        Celery_Salt: JSON.parse(response.data[0].Vodka),
        Celery: JSON.parse(response.data[0].Vodka),
        Chambord_Raspberry_Liqueur: JSON.parse(response.data[0].Vodka),
        Champagne: JSON.parse(response.data[0].Vodka),
        Cherries: JSON.parse(response.data[0].Vodka),
        Cherry_Brandy: JSON.parse(response.data[0].Vodka),
        Cherry_Cola: JSON.parse(response.data[0].Vodka),
        Cherry_Grenadine: JSON.parse(response.data[0].Vodka),
        Cherry_Heering: JSON.parse(response.data[0].Vodka),
        Cherry_Juice: JSON.parse(response.data[0].Vodka),
        Cherry_Liqueur: JSON.parse(response.data[0].Vodka),
        Cherry: JSON.parse(response.data[0].Vodka),
        Chocolate_Ice_cream: JSON.parse(response.data[0].Vodka),
        Chocolate_Liqueur: JSON.parse(response.data[0].Vodka),
        Chocolate_Milk: JSON.parse(response.data[0].Vodka),
        Chocolate_Syrup: JSON.parse(response.data[0].Vodka),
        Chocolate: JSON.parse(response.data[0].Vodka),
        Cider: JSON.parse(response.data[0].Vodka),
        Cinnamon_Schnapps: JSON.parse(response.data[0].Vodka),
        Cinnamon: JSON.parse(response.data[0].Vodka),
        Citrus_Vodka: JSON.parse(response.data[0].Vodka),
        Clamato_Juice: JSON.parse(response.data[0].Vodka),
        Cloves: JSON.parse(response.data[0].Vodka),
        Club_Soda: JSON.parse(response.data[0].Vodka),
        Coca_Cola: JSON.parse(response.data[0].Vodka),
        Cocktail_Onion: JSON.parse(response.data[0].Vodka),
        Cocoa_Powder: JSON.parse(response.data[0].Vodka),
        Coconut_Cream: JSON.parse(response.data[0].Vodka),
        Coconut_Liqueur: JSON.parse(response.data[0].Vodka),
        Coconut_Milk: JSON.parse(response.data[0].Vodka),
        Coconut_Rum: JSON.parse(response.data[0].Vodka),
        Coconut_Syrup: JSON.parse(response.data[0].Vodka),
        Coffee_Brandy: JSON.parse(response.data[0].Vodka),
        Coffee_Liqueur: JSON.parse(response.data[0].Vodka),
        Coffee: JSON.parse(response.data[0].Vodka),
        Cognac: JSON.parse(response.data[0].Vodka),
        Cointreau: JSON.parse(response.data[0].Vodka),
        Cola: JSON.parse(response.data[0].Vodka),
        Cold_Water: JSON.parse(response.data[0].Vodka),
        Condensed_Milk: JSON.parse(response.data[0].Vodka),
        Coriander: JSON.parse(response.data[0].Vodka),
        Corn_Syrup: JSON.parse(response.data[0].Vodka),
        Cornstarch: JSON.parse(response.data[0].Vodka),
        Corona: JSON.parse(response.data[0].Vodka),
        Cranberries: JSON.parse(response.data[0].Vodka),
        Cranberry_Juice: JSON.parse(response.data[0].Vodka),
        Cranberry_Liqueur: JSON.parse(response.data[0].Vodka),
        Cranberry_Vodka: JSON.parse(response.data[0].Vodka),
        Cream_of_Coconut: JSON.parse(response.data[0].Vodka),
        Cream_Sherry: JSON.parse(response.data[0].Vodka),
        Cream_Soda: JSON.parse(response.data[0].Vodka),
        Cream: JSON.parse(response.data[0].Vodka),
        Creme_De_Almond: JSON.parse(response.data[0].Vodka),
        Creme_De_Banane: JSON.parse(response.data[0].Vodka),
        Creme_De_Cacao: JSON.parse(response.data[0].Vodka),
        Creme_De_Cassis: JSON.parse(response.data[0].Vodka),
        Creme_De_Noyaux: JSON.parse(response.data[0].Vodka),
        Creme_Fraiche: JSON.parse(response.data[0].Vodka),
        Crown_Royal: JSON.parse(response.data[0].Vodka),
        Crystal_Light: JSON.parse(response.data[0].Vodka),
        Cucumber: JSON.parse(response.data[0].Vodka),
        Cumin_Powder: JSON.parse(response.data[0].Vodka),
        Cumin_Seed: JSON.parse(response.data[0].Vodka),
        Curacao: JSON.parse(response.data[0].Vodka),
        Cynar: JSON.parse(response.data[0].Vodka),
        Daiquiri_Mix: JSON.parse(response.data[0].Vodka),
        Dark_Chocolate: JSON.parse(response.data[0].Vodka),
        Dark_Creme_De_Cacao: JSON.parse(response.data[0].Vodka),
        Dark_Rum: JSON.parse(response.data[0].Vodka),
        Dark_Soy_Sauce: JSON.parse(response.data[0].Vodka),
        Demerara_Sugar: JSON.parse(response.data[0].Vodka),
        Dr_Pepper: JSON.parse(response.data[0].Vodka),
        Drambuie: JSON.parse(response.data[0].Vodka),
        Dried_Oregano: JSON.parse(response.data[0].Vodka),
        Dry_Vermouth: JSON.parse(response.data[0].Vodka),
        Dubonnet_Blanc: JSON.parse(response.data[0].Vodka),
        Dubonnet_Rouge: JSON.parse(response.data[0].Vodka),
        Egg_White: JSON.parse(response.data[0].Vodka),
        Egg_Yolk: JSON.parse(response.data[0].Vodka),
        Egg: JSON.parse(response.data[0].Vodka),
        Eggnog: JSON.parse(response.data[0].Vodka),
        Erin_Cream: JSON.parse(response.data[0].Vodka),
        Espresso: JSON.parse(response.data[0].Vodka),
        Everclear: JSON.parse(response.data[0].Vodka),
        Fanta: JSON.parse(response.data[0].Vodka),
        Fennel_Seeds: JSON.parse(response.data[0].Vodka),
        Firewater: JSON.parse(response.data[0].Vodka),
        Flaked_Almonds: JSON.parse(response.data[0].Vodka),
        Food_Coloring: JSON.parse(response.data[0].Vodka),
        Forbidden_Fruit: JSON.parse(response.data[0].Vodka),
        Frangelico: JSON.parse(response.data[0].Vodka),
        Fresca: JSON.parse(response.data[0].Vodka),
        Fresh_Basil: JSON.parse(response.data[0].Vodka),
        Fresh_Lemon_Juice: JSON.parse(response.data[0].Vodka),
        Fruit_Juice: JSON.parse(response.data[0].Vodka),
        Fruit_Punch: JSON.parse(response.data[0].Vodka),
        Fruit: JSON.parse(response.data[0].Vodka),
        Galliano: JSON.parse(response.data[0].Vodka),
        Garlic_Sauce: JSON.parse(response.data[0].Vodka),
        Gatorade: JSON.parse(response.data[0].Vodka),
        Ginger_Ale: JSON.parse(response.data[0].Vodka),
        Ginger_Beer: JSON.parse(response.data[0].Vodka),
        Ginger: JSON.parse(response.data[0].Vodka),
        Glycerine: JSON.parse(response.data[0].Vodka),
        Godiva_Liqueur: JSON.parse(response.data[0].Vodka),
        Gold_rum: JSON.parse(response.data[0].Vodka),
        Gold_Tequila: JSON.parse(response.data[0].Vodka),
        Goldschlager: JSON.parse(response.data[0].Vodka),
        Grain_Alcohol: JSON.parse(response.data[0].Vodka),
        Grand_Marnier: JSON.parse(response.data[0].Vodka),
        Granulated_Sugar: JSON.parse(response.data[0].Vodka),
        Grape_juice: JSON.parse(response.data[0].Vodka),
        Grape_soda: JSON.parse(response.data[0].Vodka),
        Grapefruit_Juice: JSON.parse(response.data[0].Vodka),
        Grapes: JSON.parse(response.data[0].Vodka),
        Green_Chartreuse: JSON.parse(response.data[0].Vodka),
        Green_Creme_de_Menthe: JSON.parse(response.data[0].Vodka),
        Green_Ginger_Wine: JSON.parse(response.data[0].Vodka),
        Green_Olives: JSON.parse(response.data[0].Vodka),
        Grenadine: JSON.parse(response.data[0].Vodka),
        Ground_Ginger: JSON.parse(response.data[0].Vodka),
        Guava_juice: JSON.parse(response.data[0].Vodka),
        Guinness_stout: JSON.parse(response.data[0].Vodka),
        Guinness: JSON.parse(response.data[0].Vodka),
        Half_and_half: JSON.parse(response.data[0].Vodka),
        Hawaiian_punch: JSON.parse(response.data[0].Vodka),
        Hazelnut_liqueur: JSON.parse(response.data[0].Vodka),
        Heavy_cream: JSON.parse(response.data[0].Vodka),
        Honey: JSON.parse(response.data[0].Vodka),
        Hooch: JSON.parse(response.data[0].Vodka),
        Hot_Chocolate: JSON.parse(response.data[0].Vodka),
        Hot_Damn: JSON.parse(response.data[0].Vodka),
        Hot_Sauce: JSON.parse(response.data[0].Vodka),
        Hpnotiq: JSON.parse(response.data[0].Vodka),
        Ice_Cream: JSON.parse(response.data[0].Vodka),
        Ice: JSON.parse(response.data[0].Vodka),
        Iced_tea: JSON.parse(response.data[0].Vodka),
        Irish_cream: JSON.parse(response.data[0].Vodka),
        Irish_Whiskey: JSON.parse(response.data[0].Vodka),
        Jack_Daniels: JSON.parse(response.data[0].Vodka),
        Jello: JSON.parse(response.data[0].Vodka),
        Jelly: JSON.parse(response.data[0].Vodka),
        Jagermeister: JSON.parse(response.data[0].Vodka),
        Jim_Beam: JSON.parse(response.data[0].Vodka),
        Johnnie_Walker: JSON.parse(response.data[0].Vodka),
        Kahlua: JSON.parse(response.data[0].Vodka),
        Key_Largo_Schnapps: JSON.parse(response.data[0].Vodka),
        Kirschwasser: JSON.parse(response.data[0].Vodka),
        Kiwi_liqueur: JSON.parse(response.data[0].Vodka),
        Kiwi: JSON.parse(response.data[0].Vodka),
        Kool_Aid: JSON.parse(response.data[0].Vodka),
        Kummel: JSON.parse(response.data[0].Vodka),
        Lager: JSON.parse(response.data[0].Vodka),
        Lemon_Juice: JSON.parse(response.data[0].Vodka),
        Lemon_Peel: JSON.parse(response.data[0].Vodka),
        Lemon_soda: JSON.parse(response.data[0].Vodka),
        Lemon_vodka: JSON.parse(response.data[0].Vodka),
        Lemon_lime_soda: JSON.parse(response.data[0].Vodka),
        lemon_lime: JSON.parse(response.data[0].Vodka),
        lemon: JSON.parse(response.data[0].Vodka),
        Lemonade: JSON.parse(response.data[0].Vodka),
        Licorice_Root: JSON.parse(response.data[0].Vodka),
        Light_Cream: JSON.parse(response.data[0].Vodka),
        Light_Rum: JSON.parse(response.data[0].Vodka),
        Lillet: JSON.parse(response.data[0].Vodka),
        Lime_juice_cordial: JSON.parse(response.data[0].Vodka),
        Lime_Juice: JSON.parse(response.data[0].Vodka),
        Lime_liqueur: JSON.parse(response.data[0].Vodka),
        Lime_Peel: JSON.parse(response.data[0].Vodka),
        Lime_vodka: JSON.parse(response.data[0].Vodka),
        Lime: JSON.parse(response.data[0].Vodka),
        Limeade: JSON.parse(response.data[0].Vodka),
        Madeira: JSON.parse(response.data[0].Vodka),
        Malibu_Rum: JSON.parse(response.data[0].Vodka),
        Mandarin: JSON.parse(response.data[0].Vodka),
        Mandarine_napoleon: JSON.parse(response.data[0].Vodka),
        Mango: JSON.parse(response.data[0].Vodka),
        Maple_syrup: JSON.parse(response.data[0].Vodka),
        Maraschino_cherry_juice: JSON.parse(response.data[0].Vodka),
        Maraschino_Cherry: JSON.parse(response.data[0].Vodka),
        Maraschino_Liqueur: JSON.parse(response.data[0].Vodka),
        Margarita_mix: JSON.parse(response.data[0].Vodka),
        Marjoram_leaves: JSON.parse(response.data[0].Vodka),
        Marshmallows: JSON.parse(response.data[0].Vodka),
        Maui: JSON.parse(response.data[0].Vodka),
        Melon_Liqueur: JSON.parse(response.data[0].Vodka),
        Melon_Vodka: JSON.parse(response.data[0].Vodka),
        Mezcal: JSON.parse(response.data[0].Vodka),
        Midori_Melon_Liqueur: JSON.parse(response.data[0].Vodka),
        Midori: JSON.parse(response.data[0].Vodka),
        Milk: JSON.parse(response.data[0].Vodka),
        Mint_syrup: JSON.parse(response.data[0].Vodka),
        Mint: JSON.parse(response.data[0].Vodka),
        Mountain_Dew: JSON.parse(response.data[0].Vodka),
        Nutmeg: JSON.parse(response.data[0].Vodka),
        Olive_Oil: JSON.parse(response.data[0].Vodka),
        Olive: JSON.parse(response.data[0].Vodka),
        Onion: JSON.parse(response.data[0].Vodka),
        Orange_Bitters: JSON.parse(response.data[0].Vodka),
        Orange_Curacao: JSON.parse(response.data[0].Vodka),
        Orange_Juice: JSON.parse(response.data[0].Vodka),
        Orange_liqueur: JSON.parse(response.data[0].Vodka),
        Orange_Peel: JSON.parse(response.data[0].Vodka),
        Orange_rum: JSON.parse(response.data[0].Vodka),
        Orange_Soda: JSON.parse(response.data[0].Vodka),
        Orange_spiral: JSON.parse(response.data[0].Vodka),
        Orange_vodka: JSON.parse(response.data[0].Vodka),
        Orange: JSON.parse(response.data[0].Vodka),
        Oreo_cookie: JSON.parse(response.data[0].Vodka),
        Orgeat_Syrup: JSON.parse(response.data[0].Vodka),
        Ouzo: JSON.parse(response.data[0].Vodka),
        Oyster_Sauce: JSON.parse(response.data[0].Vodka),
        Papaya_juice: JSON.parse(response.data[0].Vodka),
        Papaya: JSON.parse(response.data[0].Vodka),
        Parfait_amour: JSON.parse(response.data[0].Vodka),
        Passion_fruit_juice: JSON.parse(response.data[0].Vodka),
        Passion_fruit_syrup: JSON.parse(response.data[0].Vodka),
        Passoa: JSON.parse(response.data[0].Vodka),
        Peach_brandy: JSON.parse(response.data[0].Vodka),
        Peach_juice: JSON.parse(response.data[0].Vodka),
        Peach_liqueur: JSON.parse(response.data[0].Vodka),
        Peach_Nectar: JSON.parse(response.data[0].Vodka),
        Peach_Schnapps: JSON.parse(response.data[0].Vodka),
        Peach_Vodka: JSON.parse(response.data[0].Vodka),
        Peach: JSON.parse(response.data[0].Vodka),
        Peachtree_schnapps: JSON.parse(response.data[0].Vodka),
        Peanut_Oil: JSON.parse(response.data[0].Vodka),
        Pepper: JSON.parse(response.data[0].Vodka),
        Peppermint_extract: JSON.parse(response.data[0].Vodka),
        Peppermint_Schnapps: JSON.parse(response.data[0].Vodka),
        Pepsi_Cola: JSON.parse(response.data[0].Vodka),
        Pernod: JSON.parse(response.data[0].Vodka),
        Peychaud_bitters: JSON.parse(response.data[0].Vodka),
        Pina_colada_mix: JSON.parse(response.data[0].Vodka),
        Pineapple_Juice: JSON.parse(response.data[0].Vodka),
        Pineapple_rum: JSON.parse(response.data[0].Vodka),
        Pineapple_vodka: JSON.parse(response.data[0].Vodka),
        Pineapple_orange_banana_juice: JSON.parse(response.data[0].Vodka),
        Pineapple: JSON.parse(response.data[0].Vodka),
        Pink_lemonade: JSON.parse(response.data[0].Vodka),
        Pisang_Ambon: JSON.parse(response.data[0].Vodka),
        Pisco: JSON.parse(response.data[0].Vodka),
        Plain_Chocolate: JSON.parse(response.data[0].Vodka),
        Plain_Flour: JSON.parse(response.data[0].Vodka),
        Plums: JSON.parse(response.data[0].Vodka),
        Port: JSON.parse(response.data[0].Vodka),
        Powdered_Sugar: JSON.parse(response.data[0].Vodka),
        Purple_passion: JSON.parse(response.data[0].Vodka),
        Raisins: JSON.parse(response.data[0].Vodka),
        Raspberry_cordial: JSON.parse(response.data[0].Vodka),
        Raspberry_Jam: JSON.parse(response.data[0].Vodka),
        Raspberry_Juice: JSON.parse(response.data[0].Vodka),
        Raspberry_Liqueur: JSON.parse(response.data[0].Vodka),
        Raspberry_schnapps: JSON.parse(response.data[0].Vodka),
        Raspberry_syrup: JSON.parse(response.data[0].Vodka),
        Raspberry_Vodka: JSON.parse(response.data[0].Vodka),
        Red_Chile_Flakes: JSON.parse(response.data[0].Vodka),
        Red_Chili_Flakes: JSON.parse(response.data[0].Vodka),
        Red_Hot_Chili_Flakes: JSON.parse(response.data[0].Vodka),
        Red_Wine: JSON.parse(response.data[0].Vodka),
        Rhubarb: JSON.parse(response.data[0].Vodka),
        Ricard: JSON.parse(response.data[0].Vodka),
        Rock_Salt: JSON.parse(response.data[0].Vodka),
        Root_beer_schnapps: JSON.parse(response.data[0].Vodka),
        Root_beer: JSON.parse(response.data[0].Vodka),
        Roses_sweetened_lime_juice: JSON.parse(response.data[0].Vodka),
        Rosewater: JSON.parse(response.data[0].Vodka),
        Rumple_Minze: JSON.parse(response.data[0].Vodka),
        Rye_Whiskey: JSON.parse(response.data[0].Vodka),
        Sake: JSON.parse(response.data[0].Vodka),
        Salt: JSON.parse(response.data[0].Vodka),
        Sambuca: JSON.parse(response.data[0].Vodka),
        Sarsaparilla: JSON.parse(response.data[0].Vodka),
        Schnapps: JSON.parse(response.data[0].Vodka),
        Schweppes_Lemon: JSON.parse(response.data[0].Vodka),
        Schweppes_Russchian: JSON.parse(response.data[0].Vodka),
        Sherbet: JSON.parse(response.data[0].Vodka),
        Sherry: JSON.parse(response.data[0].Vodka),
        Sirup_of_roses: JSON.parse(response.data[0].Vodka),
        Sloe_Gin: JSON.parse(response.data[0].Vodka),
        Soda_Water: JSON.parse(response.data[0].Vodka),
        Sour_Apple_Pucker: JSON.parse(response.data[0].Vodka),
        Sour_Mix: JSON.parse(response.data[0].Vodka),
        Southern_Comfort: JSON.parse(response.data[0].Vodka),
        Soy_Milk: JSON.parse(response.data[0].Vodka),
        Soy_Sauce: JSON.parse(response.data[0].Vodka),
        Soya_Milk: JSON.parse(response.data[0].Vodka),
        Soya_Sauce: JSON.parse(response.data[0].Vodka),
        Spiced_Rum: JSON.parse(response.data[0].Vodka),
        Sprite: JSON.parse(response.data[0].Vodka),
        Squeezed_Orange: JSON.parse(response.data[0].Vodka),
        Squirt: JSON.parse(response.data[0].Vodka),
        Strawberries: JSON.parse(response.data[0].Vodka),
        Strawberry_juice: JSON.parse(response.data[0].Vodka),
        Strawberry_liqueur: JSON.parse(response.data[0].Vodka),
        Strawberry_Schnapps: JSON.parse(response.data[0].Vodka),
        Strawberry_syrup: JSON.parse(response.data[0].Vodka),
        Sugar_Syrup: JSON.parse(response.data[0].Vodka),
        Sugar: JSON.parse(response.data[0].Vodka),
        Sunny_delight: JSON.parse(response.data[0].Vodka),
        Surge: JSON.parse(response.data[0].Vodka),
        Swedish_punsch: JSON.parse(response.data[0].Vodka),
        Sweet_and_Sour: JSON.parse(response.data[0].Vodka),
        Sweet_Cream: JSON.parse(response.data[0].Vodka),
        Sweet_Vermouth: JSON.parse(response.data[0].Vodka),
        Tabasco_Sauce: JSON.parse(response.data[0].Vodka),
        Tang: JSON.parse(response.data[0].Vodka),
        Tawny_port: JSON.parse(response.data[0].Vodka),
        Tea: JSON.parse(response.data[0].Vodka),
        Tennessee_whiskey: JSON.parse(response.data[0].Vodka),
        Tequila_rose: JSON.parse(response.data[0].Vodka),
        Tia_Maria: JSON.parse(response.data[0].Vodka),
        Tomato_Juice: JSON.parse(response.data[0].Vodka),
        Tomato: JSON.parse(response.data[0].Vodka),
        Tonic_Water: JSON.parse(response.data[0].Vodka),
        Triple_Sec: JSON.parse(response.data[0].Vodka),
        Tropicana: JSON.parse(response.data[0].Vodka),
        Tuaca: JSON.parse(response.data[0].Vodka),
        Vanilla_extract: JSON.parse(response.data[0].Vodka),
        Vanilla_Ice_Cream: JSON.parse(response.data[0].Vodka),
        Vanilla_liqueur: JSON.parse(response.data[0].Vodka),
        Vanilla_schnapps: JSON.parse(response.data[0].Vodka),
        Vanilla_syrup: JSON.parse(response.data[0].Vodka),
        Vanilla_vodka: JSON.parse(response.data[0].Vodka),
        Vanilla: JSON.parse(response.data[0].Vodka),
        Vermouth: JSON.parse(response.data[0].Vodka),
        Vinegar: JSON.parse(response.data[0].Vodka),
        Water: JSON.parse(response.data[0].Vodka),
        Watermelon_schnapps: JSON.parse(response.data[0].Vodka),
        Whipped_Cream: JSON.parse(response.data[0].Vodka),
        Whipping_Cream: JSON.parse(response.data[0].Vodka),
        White_chocolate_liqueur: JSON.parse(response.data[0].Vodka),
        White_Creme_de_Menthe: JSON.parse(response.data[0].Vodka),
        White_grape_juice: JSON.parse(response.data[0].Vodka),
        White_port: JSON.parse(response.data[0].Vodka),
        White_Rum: JSON.parse(response.data[0].Vodka),
        White_Vinegar: JSON.parse(response.data[0].Vodka),
        White_Wine: JSON.parse(response.data[0].Vodka),
        Wild_Turkey: JSON.parse(response.data[0].Vodka),
        Wildberry_schnapps: JSON.parse(response.data[0].Vodka),
        Wine: JSON.parse(response.data[0].Vodka),
        Worcestershire_Sauce: JSON.parse(response.data[0].Vodka),
        Wormwood: JSON.parse(response.data[0].Vodka),
        Yeast: JSON.parse(response.data[0].Vodka),
        Yellow_Chartreuse: JSON.parse(response.data[0].Vodka),
        Yoghurt: JSON.parse(response.data[0].Vodka),
        Yukon_Jack: JSON.parse(response.data[0].Vodka),
        Zima: JSON.parse(response.data[0].Vodka),
        Caramel_Sauce: JSON.parse(response.data[0].Vodka),
        Chocolate_Sauce: JSON.parse(response.data[0].Vodka),
        Lillet_Blanc: JSON.parse(response.data[0].Vodka),
        Peach_Bitters: JSON.parse(response.data[0].Vodka),
        Mini_snickers_bars: JSON.parse(response.data[0].Vodka),
        Prosecco: JSON.parse(response.data[0].Vodka),
        Salted_Chocolate: JSON.parse(response.data[0].Vodka),
        Martini_Rosso: JSON.parse(response.data[0].Vodka),
        Martini_Bianco: JSON.parse(response.data[0].Vodka),
        Martini_Extra_Dry: JSON.parse(response.data[0].Vodka),
        Fresh_Lime_Juice: JSON.parse(response.data[0].Vodka),
        Fresh_Mint: JSON.parse(response.data[0].Vodka),
        Rosemary: JSON.parse(response.data[0].Vodka),
        Habanero_Peppers: JSON.parse(response.data[0].Vodka),
        Ilegal_Joven_mezcal: JSON.parse(response.data[0].Vodka),
        Elderflower_cordial: JSON.parse(response.data[0].Vodka),
        Rosso_Vermouth: JSON.parse(response.data[0].Vodka),
        Creme_de_Violette: JSON.parse(response.data[0].Vodka),
        Cocchi_Americano: JSON.parse(response.data[0].Vodka),
        White_Vermouth: JSON.parse(response.data[0].Vodka),
        Dry_Curacao: JSON.parse(response.data[0].Vodka),
        Nocino: JSON.parse(response.data[0].Vodka),
        Averna: JSON.parse(response.data[0].Vodka),
        Ramazzotti: JSON.parse(response.data[0].Vodka),
        Fernet_Branca: JSON.parse(response.data[0].Vodka),
        Allspice_Dram: JSON.parse(response.data[0].Vodka),
        Falernum: JSON.parse(response.data[0].Vodka),
        Singani: JSON.parse(response.data[0].Vodka),
        Arrack: JSON.parse(response.data[0].Vodka),
        Blackstrap_rum: JSON.parse(response.data[0].Vodka),
        Ginger_Syrup: JSON.parse(response.data[0].Vodka),
        Honey_syrup: JSON.parse(response.data[0].Vodka),
        Blended_Scotch: JSON.parse(response.data[0].Vodka),
        Islay_single_malt_Scotch: JSON.parse(response.data[0].Vodka),
        One_Fifty_One_proof_rum: JSON.parse(response.data[0].Vodka),
        Seven_up: JSON.parse(response.data[0].Vodka),
        Absinthe: JSON.parse(response.data[0].Vodka),
        Absolut_citron: JSON.parse(response.data[0].Vodka),
        Creme_de_Mure: JSON.parse(response.data[0].Vodka),
        Olive_Brine: JSON.parse(response.data[0].Vodka),
        Pineapple_Syrup: JSON.parse(response.data[0].Vodka),
        St_Germain: JSON.parse(response.data[0].Vodka),
        Lavender: JSON.parse(response.data[0].Vodka),
        Whiskey: JSON.parse(response.data[0].Vodka),
        Whisky:response.JSON.parse(response.data[0].Vodka),
      })