import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';

import IngredientSelector from './IngredientSelector.jsx';
import DrinkList from './DrinkList.jsx';
import Drink from './Drink.jsx';
import CompleteDrinkInfo from './CompleteDrinkInfo.jsx';
class Landing extends Component {
  constructor(props) {
    super(props);

    this.state = {
      Vodka: false,
      Gin: false,
      Rum: false,
      Tequila: false,
      Scotch: false,
      Absolut_Kurant: false,
      Absolut_Peppar: false,
      Absolut_Vodka: false,
      Advocaat: false,
      Aejo_Rum: false,
      Aftershock: false,
      Agave_Syrup: false,
      Ale: false,
      Allspice: false,
      Almond_Extract: false,
      Almond_Flavoring: false,
      Almond: false,
      Amaretto: false,
      Angelica_Root: false,
      Angostura_Bitters: false,
      Anis: false,
      Anise: false,
      Anisette: false,
      Aperol: false,
      Apfelkorn: false,
      Apple_Brandy: false,
      Apple_Cider: false,
      Apple_Juice: false,
      Apple_Schnapps: false,
      Apple: false,
      Applejack: false,
      Apricot_Brandy: false,
      Apricot_Nectar: false,
      Apricot: false,
      Aquavit: false,
      Asafoetida: false,
      Añejo_Rum: false,
      Bacardi_Limon: false,
      Bacardi: false,
      Baileys_Irish_Cream: false,
      Banana_Liqueur: false,
      Banana_Rum: false,
      Banana_Syrup: false,
      Banana: false,
      Barenjager: false,
      Basil: false,
      Beef_Stock: false,
      Beer: false,
      Benedictine: false,
      Berries: false,
      Bitter_lemon: false,
      Bitters: false,
      Black_Pepper: false,
      Black_Rum: false,
      Black_Sambuca: false,
      Blackberries: false,
      Blackberry_Brandy: false,
      Blackberry_Schnapps: false,
      Blackcurrant_Cordial: false,
      Blackcurrant_Schnapps: false,
      Blackcurrant_Squash: false,
      Blended_Whiskey: false,
      Blue_Curacao: false,
      Blue_Maui: false,
      Blueberries: false,
      Blueberry_Schnapps: false,
      Bourbon: false,
      Brandy: false,
      Brown_Sugar: false,
      Butter: false,
      Butterscotch_Schnapps: false,
      Cachaca: false,
      Calvados: false,
      Campari: false,
      Canadian_Whisky: false,
      Candy: false,
      Cantaloupe: false,
      Caramel_Coloring: false,
      Carbonated_Soft_Drink: false,
      Carbonated_Water: false,
      Cardamom: false,
      Cayenne_Pepper: false,
      Celery_Salt: false,
      Celery: false,
      Chambord_Raspberry_Liqueur: false,
      Champagne: false,
      Cherries: false,
      Cherry_Brandy: false,
      Cherry_Cola: false,
      Cherry_Grenadine: false,
      Cherry_Heering: false,
      Cherry_Juice: false,
      Cherry_Liqueur: false,
      Cherry: false,
      Chocolate_Ice_cream: false,   //Chocolate_Ice-cream
      Chocolate_Liqueur: false,
      Chocolate_Milk: false,
      Chocolate_Syrup: false,
      Chocolate: false,
      Cider: false,
      Cinnamon_Schnapps: false,
      Cinnamon: false,
      Citrus_Vodka: false,
      Clamato_Juice: false,
      Cloves: false,
      Club_Soda: false,
      Coca_Cola: false,  //Coca-Cola
      Cocktail_Onion: false,
      Cocoa_Powder: false,
      Coconut_Cream: false,
      Coconut_Liqueur: false,
      Coconut_Milk: false,
      Coconut_Rum: false,
      Coconut_Syrup: false,
      Coffee_Brandy: false,
      Coffee_Liqueur: false,
      Coffee: false,
      Cognac: false,
      Cointreau: false,
      Cola: false,
      Cold_Water: false,
      Condensed_Milk: false,
      Coriander: false,
      Corn_Syrup: false,
      Cornstarch: false,
      Corona: false,
      Cranberries: false,
      Cranberry_Juice: false,
      Cranberry_Liqueur: false,
      Cranberry_Vodka: false,
      Cream_of_Coconut: false,
      Cream_Sherry: false,
      Cream_Soda: false,
      Cream: false,
      Creme_De_Almond: false,
      Creme_De_Banane: false,
      Creme_De_Cacao: false,
      Creme_De_Cassis: false,
      Creme_De_Noyaux: false,
      Creme_Fraiche: false,
      Crown_Royal: false,
      Crystal_Light: false,
      Cucumber: false,
      Cumin_Powder: false,
      Cumin_Seed: false,
      Curacao: false,
      Cynar: false,
      Daiquiri_Mix: false,
      Dark_Chocolate: false,
      Dark_Creme_De_Cacao: false,
      Dark_Rum: false,
      Dark_Soy_Sauce: false,
      Demerara_Sugar: false,
      Dr_Pepper: false,  //Dr._Pepper
      Drambuie: false,
      Dried_Oregano: false,
      Dry_Vermouth: false,
      Dubonnet_Blanc: false,
      Dubonnet_Rouge: false,
      Egg_White: false,
      Egg_Yolk: false,
      Egg: false,
      Eggnog: false,
      Erin_Cream: false,
      Espresso: false,
      Everclear: false,
      Fanta: false,
      Fennel_Seeds: false,
      Firewater: false,
      Flaked_Almonds: false,
      Food_Coloring: false,
      Forbidden_Fruit: false,
      Frangelico: false,
      Fresca: false,
      Fresh_Basil: false,
      Fresh_Lemon_Juice: false,
      Fruit_Juice: false,
      Fruit_Punch: false,
      Fruit: false,
      Galliano: false,
      Garlic_Sauce: false,
      Gatorade: false,
      Ginger_Ale: false,
      Ginger_Beer: false,
      Ginger: false,
      Glycerine: false,
      Godiva_Liqueur: false,
      Gold_rum: false,
      Gold_Tequila: false,
      Goldschlager: false,
      Grain_Alcohol: false,
      Grand_Marnier: false,
      Granulated_Sugar: false,
      Grape_juice: false,
      Grape_soda: false,
      Grapefruit_Juice: false,
      Grapes: false,
      Green_Chartreuse: false,
      Green_Creme_de_Menthe: false,
      Green_Ginger_Wine: false,
      Green_Olives: false,
      Grenadine: false,
      Ground_Ginger: false,
      Guava_juice: false,
      Guinness_stout: false,
      Guinness: false,
      Half_and_half: false,  //Half-and-half
      Hawaiian_punch: false,
      Hazelnut_liqueur: false,
      Heavy_cream: false,
      Honey: false,
      Hooch: false,
      Hot_Chocolate: false,
      Hot_Damn: false,
      Hot_Sauce: false,
      Hpnotiq: false,
      Ice_Cream: false,  //Ice-Cream
      Ice: false,
      Iced_tea: false,
      Irish_cream: false,
      Irish_Whiskey: false,
      Jack_Daniels: false,
      Jello: false,
      Jelly: false,
      Jagermeister: false,
      Jim_Beam: false,
      Johnnie_Walker: false,
      Kahlua: false,
      Key_Largo_Schnapps: false,
      Kirschwasser: false,
      Kiwi_liqueur: false,
      Kiwi: false,
      Kool_Aid: false,  //Kool-Aid
      Kummel: false,
      Lager: false,
      Lemon_Juice: false,
      Lemon_Peel: false,
      Lemon_soda: false,
      Lemon_vodka: false,
      Lemon_lime_soda: false,  //Lemon-lime_soda
      lemon_lime: false,    //lemon-lime
      lemon: false,
      Lemonade: false,
      Licorice_Root: false,
      Light_Cream: false,
      Light_Rum: false,
      Lillet: false,
      Lime_juice_cordial: false,
      Lime_Juice: false,
      Lime_liqueur: false,
      Lime_Peel: false,
      Lime_vodka: false,
      Lime: false,
      Limeade: false,
      Madeira: false,
      Malibu_Rum: false,
      Mandarin: false,
      Mandarine_napoleon: false,
      Mango: false,
      Maple_syrup: false,
      Maraschino_cherry_juice: false,
      Maraschino_Cherry: false,
      Maraschino_Liqueur: false,
      Margarita_mix: false,
      Marjoram_leaves: false,
      Marshmallows: false,
      Maui: false,
      Melon_Liqueur: false,
      Melon_Vodka: false,
      Mezcal: false,
      Midori_Melon_Liqueur: false,
      Midori: false,
      Milk: false,
      Mint_syrup: false,
      Mint: false,
      Mountain_Dew: false,
      Nutmeg: false,
      Olive_Oil: false,
      Olive: false,
      Onion: false,
      Orange_Bitters: false,
      Orange_Curacao: false,
      Orange_Juice: false,
      Orange_liqueur: false,
      Orange_Peel: false,
      Orange_rum: false,
      Orange_Soda: false,
      Orange_spiral: false,
      Orange_vodka: false,
      Orange: false,
      Oreo_cookie: false,
      Orgeat_Syrup: false,
      Ouzo: false,
      Oyster_Sauce: false,
      Papaya_juice: false,
      Papaya: false,
      Parfait_amour: false,
      Passion_fruit_juice: false,
      Passion_fruit_syrup: false,
      Passoa: false,
      Peach_brandy: false,
      Peach_juice: false,
      Peach_liqueur: false,
      Peach_Nectar: false,
      Peach_Schnapps: false,
      Peach_Vodka: false,
      Peach: false,
      Peachtree_schnapps: false,
      Peanut_Oil: false,
      Pepper: false,
      Peppermint_extract: false,
      Peppermint_Schnapps: false,
      Pepsi_Cola: false,
      Pernod: false,
      Peychaud_bitters: false,
      Pina_colada_mix: false,
      Pineapple_Juice: false,
      Pineapple_rum: false,
      Pineapple_vodka: false,
      Pineapple_orange_banana_juice: false,   //Pineapple-orange-banana_juice
      Pineapple: false,
      Pink_lemonade: false,
      Pisang_Ambon: false,
      Pisco: false,
      Plain_Chocolate: false,
      Plain_Flour: false,
      Plums: false,
      Port: false,
      Powdered_Sugar: false,
      Purple_passion: false,
      Raisins: false,
      Raspberry_cordial: false,
      Raspberry_Jam: false,
      Raspberry_Juice: false,
      Raspberry_Liqueur: false,
      Raspberry_schnapps: false,
      Raspberry_syrup: false,
      Raspberry_Vodka: false,
      Red_Chile_Flakes: false,
      Red_Chili_Flakes: false,
      Red_Hot_Chili_Flakes: false,
      Red_Wine: false,
      Rhubarb: false,
      Ricard: false,
      Rock_Salt: false,
      Root_beer_schnapps: false,
      Root_beer: false,
      Roses_sweetened_lime_juice: false,
      Rosewater: false,
      Rumple_Minze: false,
      Rye_Whiskey: false,
      Sake: false,
      Salt: false,
      Sambuca: false,
      Sarsaparilla: false,
      Schnapps: false,
      Schweppes_Lemon: false,
      Schweppes_Russchian: false,
      Sherbet: false,
      Sherry: false,
      Sirup_of_roses: false,
      Sloe_Gin: false,
      Soda_Water: false,
      Sour_Apple_Pucker: false,
      Sour_Mix: false,
      Southern_Comfort: false,
      Soy_Milk: false,
      Soy_Sauce: false,
      Soya_Milk: false,
      Soya_Sauce: false,
      Spiced_Rum: false,
      Sprite: false,
      Squeezed_Orange: false,
      Squirt: false,
      Strawberries: false,
      Strawberry_juice: false,
      Strawberry_liqueur: false,
      Strawberry_Schnapps: false,
      Strawberry_syrup: false,
      Sugar_Syrup: false,
      Sugar: false,
      Sunny_delight: false,
      Surge: false,
      Swedish_punsch: false,
      Sweet_and_Sour: false,
      Sweet_Cream: false,
      Sweet_Vermouth: false,
      Tabasco_Sauce: false,
      Tang: false,
      Tawny_port: false,
      Tea: false,
      Tennessee_whiskey: false,
      Tequila_rose: false,
      Tia_Maria: false,
      Tomato_Juice: false,
      Tomato: false,
      Tonic_Water: false,
      Triple_Sec: false,
      Tropicana: false,
      Tuaca: false,
      Vanilla_extract: false,
      Vanilla_Ice_Cream: false,   //Vanilla_Ice-Cream
      Vanilla_liqueur: false,
      Vanilla_schnapps: false,
      Vanilla_syrup: false,
      Vanilla_vodka: false,
      Vanilla: false,
      Vermouth: false,
      Vinegar: false,
      Water: false,
      Watermelon_schnapps: false,
      Whipped_Cream: false,
      Whipping_Cream: false,
      White_chocolate_liqueur: false,
      White_Creme_de_Menthe: false,
      White_grape_juice: false,
      White_port: false,
      White_Rum: false,
      White_Vinegar: false,
      White_Wine: false,
      Wild_Turkey: false,
      Wildberry_schnapps: false,
      Wine: false,
      Worcestershire_Sauce: false,
      Wormwood: false,
      Yeast: false,
      Yellow_Chartreuse: false,
      Yoghurt: false,
      Yukon_Jack: false,
      Zima: false,
      Caramel_Sauce: false,
      Chocolate_Sauce: false,
      Lillet_Blanc: false,
      Peach_Bitters: false,
      Mini_snickers_bars: false,   //Mini-snickers_bars
      Prosecco: false,
      Salted_Chocolate: false,
      Martini_Rosso: false,
      Martini_Bianco: false,
      Martini_Extra_Dry: false,
      Fresh_Lime_Juice: false,
      Fresh_Mint: false,
      Rosemary: false,
      Habanero_Peppers: false,
      Ilegal_Joven_mezcal: false,
      Elderflower_cordial: false,
      Rosso_Vermouth: false,
      Creme_de_Violette: false,
      Cocchi_Americano: false,
      White_Vermouth: false,
      Dry_Curacao: false,
      Nocino: false,
      Averna: false,
      Ramazzotti: false,
      Fernet_Branca: false,   //Fernet-Branca
      Allspice_Dram: false,
      Falernum: false,
      Singani: false,
      Arrack: false,
      Blackstrap_rum: false,
      Ginger_Syrup: false,
      Honey_syrup: false,
      Blended_Scotch: false,
      Islay_single_malt_Scotch: false,
      One_Fifty_One_proof_rum: false,    //151_proof_rum
      Seven_up: false,   ///7-up
      Absinthe: false,
      Absolut_citron: false,
      Creme_de_Mure: false,
      Olive_Brine: false,
      Pineapple_Syrup: false,
      St_Germain: false,    //St._Germain
      Lavender: false,
      Whiskey: false,
      Whisky: false,
      filterDrinks: '',
      Page: 'Landing',
      ingredientCounter: 0,
      selectedItem: {},
      listOfDrinks: []
    };

    this.addItemToBar = this.addItemToBar.bind(this);
    this.handleFilterChange = this.handleFilterChange.bind(this);
    this.renderDrinkList = this.renderDrinkList.bind(this);
    this.renderLanding = this.renderLanding.bind(this);
    this.saveIngredients = this.saveIngredients.bind(this);
    this.componentDidMount = this.componentDidMount.bind(this);
    this.renderCompleteDrinkInfo = this.renderCompleteDrinkInfo.bind(this);
    this.clearIngredients = this.clearIngredients.bind(this);
    this.findRandomDrink = this.findRandomDrink.bind(this);
    this.findTopCocktails = this.findTopCocktails.bind(this);
  }

  componentDidMount(){
    axios.get('/ingredients')
    .then(response => {
      // handle success
      let count = 0;
      for (var key in response.data[0]) {
        if (response.data[0][key] === true || response.data[0][key] === 'true') {
          count++;
        }
      }
      this.setState({
        Vodka: JSON.parse(response.data[0].Vodka),
        Gin: JSON.parse(response.data[0].Gin),
        Rum: JSON.parse(response.data[0].Rum),
        Tequila: JSON.parse(response.data[0].Tequila),
        Scotch: JSON.parse(response.data[0].Scotch),
        Absolut_Kurant: JSON.parse(response.data[0].Absolut_Kurant),
        Absolut_Peppar: JSON.parse(response.data[0].Absolut_Peppar),
        Absolut_Vodka: JSON.parse(response.data[0].Absolut_Vodka),
        Advocaat: JSON.parse(response.data[0].Advocaat),
        Aejo_Rum: JSON.parse(response.data[0].Aejo_Rum),
        Aftershock: JSON.parse(response.data[0].Aftershock),
        Agave_Syrup: JSON.parse(response.data[0].Agave_Syrup),
        Ale: JSON.parse(response.data[0].Ale),
        Allspice: JSON.parse(response.data[0].Allspice),
        Almond_Extract: JSON.parse(response.data[0].Almond_Extract),
        Almond_Flavoring: JSON.parse(response.data[0].Almond_Flavoring),
        Almond: JSON.parse(response.data[0].Almond),
        Amaretto: JSON.parse(response.data[0].Amaretto),
        Angelica_Root: JSON.parse(response.data[0].Angelica_Root),
        Angostura_Bitters: JSON.parse(response.data[0].Angostura_Bitters),
        Anis: JSON.parse(response.data[0].Anis),
        Anise: JSON.parse(response.data[0].Anise),
        Anisette: JSON.parse(response.data[0].Anisette),
        Aperol: JSON.parse(response.data[0].Aperol),
        Apfelkorn: JSON.parse(response.data[0].Apfelkorn),
        Apple_Brandy: JSON.parse(response.data[0].Apple_Brandy),
        Apple_Cider: JSON.parse(response.data[0].Apple_Cider),
        Apple_Juice: JSON.parse(response.data[0].Apple_Juice),
        Apple_Schnapps: JSON.parse(response.data[0].Apple_Schnapps),
        Apple: JSON.parse(response.data[0].Apple),
        Applejack: JSON.parse(response.data[0].Applejack),
        Apricot_Brandy: JSON.parse(response.data[0].Apricot_Brandy),
        Apricot_Nectar: JSON.parse(response.data[0].Apricot_Nectar),
        Apricot: JSON.parse(response.data[0].Apricot),
        Aquavit: JSON.parse(response.data[0].Aquavit),
        Asafoetida: JSON.parse(response.data[0].Asafoetida),
        Añejo_Rum: JSON.parse(response.data[0].Añejo_Rum),
        Bacardi_Limon: JSON.parse(response.data[0].Bacardi_Limon),
        Bacardi: JSON.parse(response.data[0].Bacardi),
        Baileys_Irish_Cream: JSON.parse(response.data[0].Baileys_Irish_Cream),
        Banana_Liqueur: JSON.parse(response.data[0].Banana_Liqueur),
        Banana_Rum: JSON.parse(response.data[0].Banana_Rum),
        Banana_Syrup: JSON.parse(response.data[0].Banana_Syrup),
        Banana: JSON.parse(response.data[0].Banana),
        Barenjager: JSON.parse(response.data[0].Barenjager),
        Basil: JSON.parse(response.data[0].Basil),
        Beef_Stock: JSON.parse(response.data[0].Beef_Stock),
        Beer: JSON.parse(response.data[0].Beer),
        Benedictine: JSON.parse(response.data[0].Benedictine),
        Berries: JSON.parse(response.data[0].Berries),
        Bitter_lemon: JSON.parse(response.data[0].Bitter_lemon),
        Bitters: JSON.parse(response.data[0].Bitters),
        Black_Pepper: JSON.parse(response.data[0].Black_Pepper),
        Black_Rum: JSON.parse(response.data[0].Black_Rum),
        Black_Sambuca: JSON.parse(response.data[0].Black_Sambuca),
        Blackberries: JSON.parse(response.data[0].Blackberries),
        Blackberry_Brandy: JSON.parse(response.data[0].Blackberry_Brandy),
        Blackberry_Schnapps: JSON.parse(response.data[0].Blackberry_Schnapps),
        Blackcurrant_Cordial: JSON.parse(response.data[0].Blackcurrant_Cordial),
        Blackcurrant_Schnapps: JSON.parse(response.data[0].Blackcurrant_Schnapps),
        Blackcurrant_Squash: JSON.parse(response.data[0].Blackcurrant_Squash),
        Blended_Whiskey: JSON.parse(response.data[0].Blended_Whiskey),
        Blue_Curacao: JSON.parse(response.data[0].Blue_Curacao),
        Blue_Maui: JSON.parse(response.data[0].Blue_Maui),
        Blueberries: JSON.parse(response.data[0].Blueberries),
        Blueberry_Schnapps: JSON.parse(response.data[0].Blueberry_Schnapps),
        Bourbon: JSON.parse(response.data[0].Bourbon),
        Brandy: JSON.parse(response.data[0].Brandy),
        Brown_Sugar: JSON.parse(response.data[0].Brown_Sugar),
        Butter: JSON.parse(response.data[0].Butter),
        Butterscotch_Schnapps: JSON.parse(response.data[0].Butterscotch_Schnapps),
        Cachaca: JSON.parse(response.data[0].Cachaca),
        Calvados: JSON.parse(response.data[0].Calvados),
        Campari: JSON.parse(response.data[0].Campari),
        Canadian_Whisky: JSON.parse(response.data[0].Canadian_Whisky),
        Candy: JSON.parse(response.data[0].Candy),
        Cantaloupe: JSON.parse(response.data[0].Cantaloupe),
        Caramel_Coloring: JSON.parse(response.data[0].Caramel_Coloring),
        Carbonated_Soft_Drink: JSON.parse(response.data[0].Carbonated_Soft_Drink),
        Carbonated_Water: JSON.parse(response.data[0].Carbonated_Water),
        Cardamom: JSON.parse(response.data[0].Cardamom),
        Cayenne_Pepper: JSON.parse(response.data[0].Cayenne_Pepper),
        Celery_Salt: JSON.parse(response.data[0].Celery_Salt),
        Celery: JSON.parse(response.data[0].Celery),
        Chambord_Raspberry_Liqueur: JSON.parse(response.data[0].Chambord_Raspberry_Liqueur),
        Champagne: JSON.parse(response.data[0].Champagne),
        Cherries: JSON.parse(response.data[0].Cherries),
        Cherry_Brandy: JSON.parse(response.data[0].Cherry_Brandy),
        Cherry_Cola: JSON.parse(response.data[0].Cherry_Cola),
        Cherry_Grenadine: JSON.parse(response.data[0].Cherry_Grenadine),
        Cherry_Heering: JSON.parse(response.data[0].Cherry_Heering),
        Cherry_Juice: JSON.parse(response.data[0].Cherry_Juice),
        Cherry_Liqueur: JSON.parse(response.data[0].Cherry_Liqueur),
        Cherry: JSON.parse(response.data[0].Cherry),
        Chocolate_Ice_cream: JSON.parse(response.data[0].Chocolate_Ice_cream),
        Chocolate_Liqueur: JSON.parse(response.data[0].Chocolate_Liqueur),
        Chocolate_Milk: JSON.parse(response.data[0].Chocolate_Milk),
        Chocolate_Syrup: JSON.parse(response.data[0].Chocolate_Syrup),
        Chocolate: JSON.parse(response.data[0].Chocolate),
        Cider: JSON.parse(response.data[0].Cider),
        Cinnamon_Schnapps: JSON.parse(response.data[0].Cinnamon_Schnapps),
        Cinnamon: JSON.parse(response.data[0].Cinnamon),
        Citrus_Vodka: JSON.parse(response.data[0].Citrus_Vodka),
        Clamato_Juice: JSON.parse(response.data[0].Clamato_Juice),
        Cloves: JSON.parse(response.data[0].Cloves),
        Club_Soda: JSON.parse(response.data[0].Club_Soda),
        Coca_Cola: JSON.parse(response.data[0].Coca_Cola),
        Cocktail_Onion: JSON.parse(response.data[0].Cocktail_Onion),
        Cocoa_Powder: JSON.parse(response.data[0].Cocoa_Powder),
        Coconut_Cream: JSON.parse(response.data[0].Coconut_Cream),
        Coconut_Liqueur: JSON.parse(response.data[0].Coconut_Liqueur),
        Coconut_Milk: JSON.parse(response.data[0].Coconut_Milk),
        Coconut_Rum: JSON.parse(response.data[0].Coconut_Rum),
        Coconut_Syrup: JSON.parse(response.data[0].Coconut_Syrup),
        Coffee_Brandy: JSON.parse(response.data[0].Coffee_Brandy),
        Coffee_Liqueur: JSON.parse(response.data[0].Coffee_Liqueur),
        Coffee: JSON.parse(response.data[0].Coffee),
        Cognac: JSON.parse(response.data[0].Cognac),
        Cointreau: JSON.parse(response.data[0].Cointreau),
        Cola: JSON.parse(response.data[0].Cola),
        Cold_Water: JSON.parse(response.data[0].Cold_Water),
        Condensed_Milk: JSON.parse(response.data[0].Condensed_Milk),
        Coriander: JSON.parse(response.data[0].Coriander),
        Corn_Syrup: JSON.parse(response.data[0].Corn_Syrup),
        Cornstarch: JSON.parse(response.data[0].Cornstarch),
        Corona: JSON.parse(response.data[0].Corona),
        Cranberries: JSON.parse(response.data[0].Cranberries),
        Cranberry_Juice: JSON.parse(response.data[0].Cranberry_Juice),
        Cranberry_Liqueur: JSON.parse(response.data[0].Cranberry_Liqueur),
        Cranberry_Vodka: JSON.parse(response.data[0].Cranberry_Vodka),
        Cream_of_Coconut: JSON.parse(response.data[0].Cream_of_Coconut),
        Cream_Sherry: JSON.parse(response.data[0].Cream_Sherry),
        Cream_Soda: JSON.parse(response.data[0].Cream_Soda),
        Cream: JSON.parse(response.data[0].Cream),
        Creme_De_Almond: JSON.parse(response.data[0].Creme_De_Almond),
        Creme_De_Banane: JSON.parse(response.data[0].Creme_De_Banane),
        Creme_De_Cacao: JSON.parse(response.data[0].Creme_De_Cacao),
        Creme_De_Cassis: JSON.parse(response.data[0].Creme_De_Cassis),
        Creme_De_Noyaux: JSON.parse(response.data[0].Creme_De_Noyaux),
        Creme_Fraiche: JSON.parse(response.data[0].Creme_Fraiche),
        Crown_Royal: JSON.parse(response.data[0].Crown_Royal),
        Crystal_Light: JSON.parse(response.data[0].Crystal_Light),
        Cucumber: JSON.parse(response.data[0].Cucumber),
        Cumin_Powder: JSON.parse(response.data[0].Cumin_Powder),
        Cumin_Seed: JSON.parse(response.data[0].Cumin_Seed),
        Curacao: JSON.parse(response.data[0].Curacao),
        Cynar: JSON.parse(response.data[0].Cynar),
        Daiquiri_Mix: JSON.parse(response.data[0].Daiquiri_Mix),
        Dark_Chocolate: JSON.parse(response.data[0].Dark_Chocolate),
        Dark_Creme_De_Cacao: JSON.parse(response.data[0].Dark_Creme_De_Cacao),
        Dark_Rum: JSON.parse(response.data[0].Dark_Rum),
        Dark_Soy_Sauce: JSON.parse(response.data[0].Dark_Soy_Sauce),
        Demerara_Sugar: JSON.parse(response.data[0].Demerara_Sugar),
        Dr_Pepper: JSON.parse(response.data[0].Dr_Pepper),
        Drambuie: JSON.parse(response.data[0].Drambuie),
        Dried_Oregano: JSON.parse(response.data[0].Dried_Oregano),
        Dry_Vermouth: JSON.parse(response.data[0].Dry_Vermouth),
        Dubonnet_Blanc: JSON.parse(response.data[0].Dubonnet_Blanc),
        Dubonnet_Rouge: JSON.parse(response.data[0].Dubonnet_Rouge),
        Egg_White: JSON.parse(response.data[0].Egg_White),
        Egg_Yolk: JSON.parse(response.data[0].Egg_Yolk),
        Egg: JSON.parse(response.data[0].Egg),
        Eggnog: JSON.parse(response.data[0].Eggnog),
        Erin_Cream: JSON.parse(response.data[0].Erin_Cream),
        Espresso: JSON.parse(response.data[0].Espresso),
        Everclear: JSON.parse(response.data[0].Everclear),
        Fanta: JSON.parse(response.data[0].Fanta),
        Fennel_Seeds: JSON.parse(response.data[0].Fennel_Seeds),
        Firewater: JSON.parse(response.data[0].Firewater),
        Flaked_Almonds: JSON.parse(response.data[0].Flaked_Almonds),
        Food_Coloring: JSON.parse(response.data[0].Food_Coloring),
        Forbidden_Fruit: JSON.parse(response.data[0].Forbidden_Fruit),
        Frangelico: JSON.parse(response.data[0].Frangelico),
        Fresca: JSON.parse(response.data[0].Fresca),
        Fresh_Basil: JSON.parse(response.data[0].Fresh_Basil),
        Fresh_Lemon_Juice: JSON.parse(response.data[0].Fresh_Lemon_Juice),
        Fruit_Juice: JSON.parse(response.data[0].Fruit_Juice),
        Fruit_Punch: JSON.parse(response.data[0].Fruit_Punch),
        Fruit: JSON.parse(response.data[0].Fruit),
        Galliano: JSON.parse(response.data[0].Galliano),
        Garlic_Sauce: JSON.parse(response.data[0].Garlic_Sauce),
        Gatorade: JSON.parse(response.data[0].Gatorade),
        Ginger_Ale: JSON.parse(response.data[0].Ginger_Ale),
        Ginger_Beer: JSON.parse(response.data[0].Ginger_Beer),
        Ginger: JSON.parse(response.data[0].Ginger),
        Glycerine: JSON.parse(response.data[0].Glycerine),
        Godiva_Liqueur: JSON.parse(response.data[0].Godiva_Liqueur),
        Gold_rum: JSON.parse(response.data[0].Gold_rum),
        Gold_Tequila: JSON.parse(response.data[0].Gold_Tequila),
        Goldschlager: JSON.parse(response.data[0].Goldschlager),
        Grain_Alcohol: JSON.parse(response.data[0].Grain_Alcohol),
        Grand_Marnier: JSON.parse(response.data[0].Grand_Marnier),
        Granulated_Sugar: JSON.parse(response.data[0].Granulated_Sugar),
        Grape_juice: JSON.parse(response.data[0].Grape_juice),
        Grape_soda: JSON.parse(response.data[0].Grape_soda),
        Grapefruit_Juice: JSON.parse(response.data[0].Grapefruit_Juice),
        Grapes: JSON.parse(response.data[0].Grapes),
        Green_Chartreuse: JSON.parse(response.data[0].Green_Chartreuse),
        Green_Creme_de_Menthe: JSON.parse(response.data[0].Green_Creme_de_Menthe),
        Green_Ginger_Wine: JSON.parse(response.data[0].Green_Ginger_Wine),
        Green_Olives: JSON.parse(response.data[0].Green_Olives),
        Grenadine: JSON.parse(response.data[0].Grenadine),
        Ground_Ginger: JSON.parse(response.data[0].Ground_Ginger),
        Guava_juice: JSON.parse(response.data[0].Guava_juice),
        Guinness_stout: JSON.parse(response.data[0].Guinness_stout),
        Guinness: JSON.parse(response.data[0].Guinness),
        Half_and_half: JSON.parse(response.data[0].Half_and_half),
        Hawaiian_punch: JSON.parse(response.data[0].Hawaiian_punch),
        Hazelnut_liqueur: JSON.parse(response.data[0].Hazelnut_liqueur),
        Heavy_cream: JSON.parse(response.data[0].Heavy_cream),
        Honey: JSON.parse(response.data[0].Honey),
        Hooch: JSON.parse(response.data[0].Hooch),
        Hot_Chocolate: JSON.parse(response.data[0].Hot_Chocolate),
        Hot_Damn: JSON.parse(response.data[0].Hot_Damn),
        Hot_Sauce: JSON.parse(response.data[0].Hot_Sauce),
        Hpnotiq: JSON.parse(response.data[0].Hpnotiq),
        Ice_Cream: JSON.parse(response.data[0].Ice_Cream),
        Ice: JSON.parse(response.data[0].Ice),
        Iced_tea: JSON.parse(response.data[0].Iced_tea),
        Irish_cream: JSON.parse(response.data[0].Irish_cream),
        Irish_Whiskey: JSON.parse(response.data[0].Irish_Whiskey),
        Jack_Daniels: JSON.parse(response.data[0].Jack_Daniels),
        Jello: JSON.parse(response.data[0].Jello),
        Jelly: JSON.parse(response.data[0].Jelly),
        Jagermeister: JSON.parse(response.data[0].Jagermeister),
        Jim_Beam: JSON.parse(response.data[0].Jim_Beam),
        Johnnie_Walker: JSON.parse(response.data[0].Johnnie_Walker),
        Kahlua: JSON.parse(response.data[0].Kahlua),
        Key_Largo_Schnapps: JSON.parse(response.data[0].Key_Largo_Schnapps),
        Kirschwasser: JSON.parse(response.data[0].Kirschwasser),
        Kiwi_liqueur: JSON.parse(response.data[0].Kiwi_liqueur),
        Kiwi: JSON.parse(response.data[0].Kiwi),
        Kool_Aid: JSON.parse(response.data[0].Kool_Aid),
        Kummel: JSON.parse(response.data[0].Kummel),
        Lager: JSON.parse(response.data[0].Lager),
        Lemon_Juice: JSON.parse(response.data[0].Lemon_Juice),
        Lemon_Peel: JSON.parse(response.data[0].Lemon_Peel),
        Lemon_soda: JSON.parse(response.data[0].Lemon_soda),
        Lemon_vodka: JSON.parse(response.data[0].Lemon_vodka),
        Lemon_lime_soda: JSON.parse(response.data[0].Lemon_lime_soda),
        lemon_lime: JSON.parse(response.data[0].lemon_lime),
        lemon: JSON.parse(response.data[0].lemon),
        Lemonade: JSON.parse(response.data[0].Lemonade),
        Licorice_Root: JSON.parse(response.data[0].Licorice_Root),
        Light_Cream: JSON.parse(response.data[0].Light_Cream),
        Light_Rum: JSON.parse(response.data[0].Light_Rum),
        Lillet: JSON.parse(response.data[0].Lillet),
        Lime_juice_cordial: JSON.parse(response.data[0].Lime_juice_cordial),
        Lime_Juice: JSON.parse(response.data[0].Lime_Juice),
        Lime_liqueur: JSON.parse(response.data[0].Lime_liqueur),
        Lime_Peel: JSON.parse(response.data[0].Lime_Peel),
        Lime_vodka: JSON.parse(response.data[0].Lime_vodka),
        Lime: JSON.parse(response.data[0].Lime),
        Limeade: JSON.parse(response.data[0].Limeade),
        Madeira: JSON.parse(response.data[0].Madeira),
        Malibu_Rum: JSON.parse(response.data[0].Malibu_Rum),
        Mandarin: JSON.parse(response.data[0].Mandarin),
        Mandarine_napoleon: JSON.parse(response.data[0].Mandarine_napoleon),
        Mango: JSON.parse(response.data[0].Mango),
        Maple_syrup: JSON.parse(response.data[0].Maple_syrup),
        Maraschino_cherry_juice: JSON.parse(response.data[0].Maraschino_cherry_juice),
        Maraschino_Cherry: JSON.parse(response.data[0].Maraschino_Cherry),
        Maraschino_Liqueur: JSON.parse(response.data[0].Maraschino_Liqueur),
        Margarita_mix: JSON.parse(response.data[0].Margarita_mix),
        Marjoram_leaves: JSON.parse(response.data[0].Marjoram_leaves),
        Marshmallows: JSON.parse(response.data[0].Marshmallows),
        Maui: JSON.parse(response.data[0].Maui),
        Melon_Liqueur: JSON.parse(response.data[0].Melon_Liqueur),
        Melon_Vodka: JSON.parse(response.data[0].Melon_Vodka),
        Mezcal: JSON.parse(response.data[0].Mezcal),
        Midori_Melon_Liqueur: JSON.parse(response.data[0].Midori_Melon_Liqueur),
        Midori: JSON.parse(response.data[0].Midori),
        Milk: JSON.parse(response.data[0].Milk),
        Mint_syrup: JSON.parse(response.data[0].Mint_syrup),
        Mint: JSON.parse(response.data[0].Mint),
        Mountain_Dew: JSON.parse(response.data[0].Mountain_Dew),
        Nutmeg: JSON.parse(response.data[0].Nutmeg),
        Olive_Oil: JSON.parse(response.data[0].Olive_Oil),
        Olive: JSON.parse(response.data[0].Olive),
        Onion: JSON.parse(response.data[0].Onion),
        Orange_Bitters: JSON.parse(response.data[0].Orange_Bitters),
        Orange_Curacao: JSON.parse(response.data[0].Orange_Curacao),
        Orange_Juice: JSON.parse(response.data[0].Orange_Juice),
        Orange_liqueur: JSON.parse(response.data[0].Orange_liqueur),
        Orange_Peel: JSON.parse(response.data[0].Orange_Peel),
        Orange_rum: JSON.parse(response.data[0].Orange_rum),
        Orange_Soda: JSON.parse(response.data[0].Orange_Soda),
        Orange_spiral: JSON.parse(response.data[0].Orange_spiral),
        Orange_vodka: JSON.parse(response.data[0].Orange_vodka),
        Orange: JSON.parse(response.data[0].Orange),
        Oreo_cookie: JSON.parse(response.data[0].Oreo_cookie),
        Orgeat_Syrup: JSON.parse(response.data[0].Orgeat_Syrup),
        Ouzo: JSON.parse(response.data[0].Ouzo),
        Oyster_Sauce: JSON.parse(response.data[0].Oyster_Sauce),
        Papaya_juice: JSON.parse(response.data[0].Papaya_juice),
        Papaya: JSON.parse(response.data[0].Papaya),
        Parfait_amour: JSON.parse(response.data[0].Parfait_amour),
        Passion_fruit_juice: JSON.parse(response.data[0].Passion_fruit_juice),
        Passion_fruit_syrup: JSON.parse(response.data[0].Passion_fruit_syrup),
        Passoa: JSON.parse(response.data[0].Passoa),
        Peach_brandy: JSON.parse(response.data[0].Peach_brandy),
        Peach_juice: JSON.parse(response.data[0].Peach_juice),
        Peach_liqueur: JSON.parse(response.data[0].Peach_liqueur),
        Peach_Nectar: JSON.parse(response.data[0].Peach_Nectar),
        Peach_Schnapps: JSON.parse(response.data[0].Peach_Schnapps),
        Peach_Vodka: JSON.parse(response.data[0].Peach_Vodka),
        Peach: JSON.parse(response.data[0].Peach),
        Peachtree_schnapps: JSON.parse(response.data[0].Peachtree_schnapps),
        Peanut_Oil: JSON.parse(response.data[0].Peanut_Oil),
        Pepper: JSON.parse(response.data[0].Pepper),
        Peppermint_extract: JSON.parse(response.data[0].Peppermint_extract),
        Peppermint_Schnapps: JSON.parse(response.data[0].Peppermint_Schnapps),
        Pepsi_Cola: JSON.parse(response.data[0].Pepsi_Cola),
        Pernod: JSON.parse(response.data[0].Pernod),
        Peychaud_bitters: JSON.parse(response.data[0].Peychaud_bitters),
        Pina_colada_mix: JSON.parse(response.data[0].Pina_colada_mix),
        Pineapple_Juice: JSON.parse(response.data[0].Pineapple_Juice),
        Pineapple_rum: JSON.parse(response.data[0].Pineapple_rum),
        Pineapple_vodka: JSON.parse(response.data[0].Pineapple_vodka),
        Pineapple_orange_banana_juice: JSON.parse(response.data[0].Pineapple_orange_banana_juice),
        Pineapple: JSON.parse(response.data[0].Pineapple),
        Pink_lemonade: JSON.parse(response.data[0].Pink_lemonade),
        Pisang_Ambon: JSON.parse(response.data[0].Pisang_Ambon),
        Pisco: JSON.parse(response.data[0].Pisco),
        Plain_Chocolate: JSON.parse(response.data[0].Plain_Chocolate),
        Plain_Flour: JSON.parse(response.data[0].Plain_Flour),
        Plums: JSON.parse(response.data[0].Plums),
        Port: JSON.parse(response.data[0].Port),
        Powdered_Sugar: JSON.parse(response.data[0].Powdered_Sugar),
        Purple_passion: JSON.parse(response.data[0].Purple_passion),
        Raisins: JSON.parse(response.data[0].Raisins),
        Raspberry_cordial: JSON.parse(response.data[0].Raspberry_cordial),
        Raspberry_Jam: JSON.parse(response.data[0].Raspberry_Jam),
        Raspberry_Juice: JSON.parse(response.data[0].Raspberry_Juice),
        Raspberry_Liqueur: JSON.parse(response.data[0].Raspberry_Liqueur),
        Raspberry_schnapps: JSON.parse(response.data[0].Raspberry_schnapps),
        Raspberry_syrup: JSON.parse(response.data[0].Raspberry_syrup),
        Raspberry_Vodka: JSON.parse(response.data[0].Raspberry_Vodka),
        Red_Chile_Flakes: JSON.parse(response.data[0].Red_Chile_Flakes),
        Red_Chili_Flakes: JSON.parse(response.data[0].Red_Chili_Flakes),
        Red_Hot_Chili_Flakes: JSON.parse(response.data[0].Red_Hot_Chili_Flakes),
        Red_Wine: JSON.parse(response.data[0].Red_Wine),
        Rhubarb: JSON.parse(response.data[0].Rhubarb),
        Ricard: JSON.parse(response.data[0].Ricard),
        Rock_Salt: JSON.parse(response.data[0].Rock_Salt),
        Root_beer_schnapps: JSON.parse(response.data[0].Root_beer_schnapps),
        Root_beer: JSON.parse(response.data[0].Root_beer),
        Roses_sweetened_lime_juice: JSON.parse(response.data[0].Roses_sweetened_lime_juice),
        Rosewater: JSON.parse(response.data[0].Rosewater),
        Rumple_Minze: JSON.parse(response.data[0].Rumple_Minze),
        Rye_Whiskey: JSON.parse(response.data[0].Rye_Whiskey),
        Sake: JSON.parse(response.data[0].Sake),
        Salt: JSON.parse(response.data[0].Salt),
        Sambuca: JSON.parse(response.data[0].Sambuca),
        Sarsaparilla: JSON.parse(response.data[0].Sarsaparilla),
        Schnapps: JSON.parse(response.data[0].Schnapps),
        Schweppes_Lemon: JSON.parse(response.data[0].Schweppes_Lemon),
        Schweppes_Russchian: JSON.parse(response.data[0].Schweppes_Russchian),
        Sherbet: JSON.parse(response.data[0].Sherbet),
        Sherry: JSON.parse(response.data[0].Sherry),
        Sirup_of_roses: JSON.parse(response.data[0].Sirup_of_roses),
        Sloe_Gin: JSON.parse(response.data[0].Sloe_Gin),
        Soda_Water: JSON.parse(response.data[0].Soda_Water),
        Sour_Apple_Pucker: JSON.parse(response.data[0].Sour_Apple_Pucker),
        Sour_Mix: JSON.parse(response.data[0].Sour_Mix),
        Southern_Comfort: JSON.parse(response.data[0].Southern_Comfort),
        Soy_Milk: JSON.parse(response.data[0].Soy_Milk),
        Soy_Sauce: JSON.parse(response.data[0].Soy_Sauce),
        Soya_Milk: JSON.parse(response.data[0].Soya_Milk),
        Soya_Sauce: JSON.parse(response.data[0].Soya_Sauce),
        Spiced_Rum: JSON.parse(response.data[0].Spiced_Rum),
        Sprite: JSON.parse(response.data[0].Sprite),
        Squeezed_Orange: JSON.parse(response.data[0].Squeezed_Orange),
        Squirt: JSON.parse(response.data[0].Squirt),
        Strawberries: JSON.parse(response.data[0].Strawberries),
        Strawberry_juice: JSON.parse(response.data[0].Strawberry_juice),
        Strawberry_liqueur: JSON.parse(response.data[0].Strawberry_liqueur),
        Strawberry_Schnapps: JSON.parse(response.data[0].Strawberry_Schnapps),
        Strawberry_syrup: JSON.parse(response.data[0].Strawberry_syrup),
        Sugar_Syrup: JSON.parse(response.data[0].Sugar_Syrup),
        Sugar: JSON.parse(response.data[0].Sugar),
        Sunny_delight: JSON.parse(response.data[0].Sunny_delight),
        Surge: JSON.parse(response.data[0].Surge),
        Swedish_punsch: JSON.parse(response.data[0].Swedish_punsch),
        Sweet_and_Sour: JSON.parse(response.data[0].Sweet_and_Sour),
        Sweet_Cream: JSON.parse(response.data[0].Sweet_Cream),
        Sweet_Vermouth: JSON.parse(response.data[0].Sweet_Vermouth),
        Tabasco_Sauce: JSON.parse(response.data[0].Tabasco_Sauce),
        Tang: JSON.parse(response.data[0].Tang),
        Tawny_port: JSON.parse(response.data[0].Tawny_port),
        Tea: JSON.parse(response.data[0].Tea),
        Tennessee_whiskey: JSON.parse(response.data[0].Tennessee_whiskey),
        Tequila_rose: JSON.parse(response.data[0].Tequila_rose),
        Tia_Maria: JSON.parse(response.data[0].Tia_Maria),
        Tomato_Juice: JSON.parse(response.data[0].Tomato_Juice),
        Tomato: JSON.parse(response.data[0].Tomato),
        Tonic_Water: JSON.parse(response.data[0].Tonic_Water),
        Triple_Sec: JSON.parse(response.data[0].Triple_Sec),
        Tropicana: JSON.parse(response.data[0].Tropicana),
        Tuaca: JSON.parse(response.data[0].Tuaca),
        Vanilla_extract: JSON.parse(response.data[0].Vanilla_extract),
        Vanilla_Ice_Cream: JSON.parse(response.data[0].Vanilla_Ice_Cream),
        Vanilla_liqueur: JSON.parse(response.data[0].Vanilla_liqueur),
        Vanilla_schnapps: JSON.parse(response.data[0].Vanilla_schnapps),
        Vanilla_syrup: JSON.parse(response.data[0].Vanilla_syrup),
        Vanilla_vodka: JSON.parse(response.data[0].Vanilla_vodka),
        Vanilla: JSON.parse(response.data[0].Vanilla),
        Vermouth: JSON.parse(response.data[0].Vermouth),
        Vinegar: JSON.parse(response.data[0].Vinegar),
        Water: JSON.parse(response.data[0].Water),
        Watermelon_schnapps: JSON.parse(response.data[0].Watermelon_schnapps),
        Whipped_Cream: JSON.parse(response.data[0].Whipped_Cream),
        Whipping_Cream: JSON.parse(response.data[0].Whipping_Cream),
        White_chocolate_liqueur: JSON.parse(response.data[0].White_chocolate_liqueur),
        White_Creme_de_Menthe: JSON.parse(response.data[0].White_Creme_de_Menthe),
        White_grape_juice: JSON.parse(response.data[0].White_grape_juice),
        White_port: JSON.parse(response.data[0].White_port),
        White_Rum: JSON.parse(response.data[0].White_Rum),
        White_Vinegar: JSON.parse(response.data[0].White_Vinegar),
        White_Wine: JSON.parse(response.data[0].White_Wine),
        Wild_Turkey: JSON.parse(response.data[0].Wild_Turkey),
        Wildberry_schnapps: JSON.parse(response.data[0].Wildberry_schnapps),
        Wine: JSON.parse(response.data[0].Wine),
        Worcestershire_Sauce: JSON.parse(response.data[0].Worcestershire_Sauce),
        Wormwood: JSON.parse(response.data[0].Wormwood),
        Yeast: JSON.parse(response.data[0].Yeast),
        Yellow_Chartreuse: JSON.parse(response.data[0].Yellow_Chartreuse),
        Yoghurt: JSON.parse(response.data[0].Yoghurt),
        Yukon_Jack: JSON.parse(response.data[0].Yukon_Jack),
        Zima: JSON.parse(response.data[0].Zima),
        Caramel_Sauce: JSON.parse(response.data[0].Caramel_Sauce),
        Chocolate_Sauce: JSON.parse(response.data[0].Chocolate_Sauce),
        Lillet_Blanc: JSON.parse(response.data[0].Lillet_Blanc),
        Peach_Bitters: JSON.parse(response.data[0].Peach_Bitters),
        Mini_snickers_bars: JSON.parse(response.data[0].Mini_snickers_bars),
        Prosecco: JSON.parse(response.data[0].Prosecco),
        Salted_Chocolate: JSON.parse(response.data[0].Salted_Chocolate),
        Martini_Rosso: JSON.parse(response.data[0].Martini_Rosso),
        Martini_Bianco: JSON.parse(response.data[0].Martini_Bianco),
        Martini_Extra_Dry: JSON.parse(response.data[0].Martini_Extra_Dry),
        Fresh_Lime_Juice: JSON.parse(response.data[0].Fresh_Lime_Juice),
        Fresh_Mint: JSON.parse(response.data[0].Fresh_Mint),
        Rosemary: JSON.parse(response.data[0].Rosemary),
        Habanero_Peppers: JSON.parse(response.data[0].Habanero_Peppers),
        Ilegal_Joven_mezcal: JSON.parse(response.data[0].Ilegal_Joven_mezcal),
        Elderflower_cordial: JSON.parse(response.data[0].Elderflower_cordial),
        Rosso_Vermouth: JSON.parse(response.data[0].Rosso_Vermouth),
        Creme_de_Violette: JSON.parse(response.data[0].Creme_de_Violette),
        Cocchi_Americano: JSON.parse(response.data[0].Cocchi_Americano),
        White_Vermouth: JSON.parse(response.data[0].White_Vermouth),
        Dry_Curacao: JSON.parse(response.data[0].Dry_Curacao),
        Nocino: JSON.parse(response.data[0].Nocino),
        Averna: JSON.parse(response.data[0].Averna),
        Ramazzotti: JSON.parse(response.data[0].Ramazzotti),
        Fernet_Branca: JSON.parse(response.data[0].Fernet_Branca),
        Allspice_Dram: JSON.parse(response.data[0].Allspice_Dram),
        Falernum: JSON.parse(response.data[0].Falernum),
        Singani: JSON.parse(response.data[0].Singani),
        Arrack: JSON.parse(response.data[0].Arrack),
        Blackstrap_rum: JSON.parse(response.data[0].Blackstrap_rum),
        Ginger_Syrup: JSON.parse(response.data[0].Ginger_Syrup),
        Honey_syrup: JSON.parse(response.data[0].Honey_syrup),
        Blended_Scotch: JSON.parse(response.data[0].Blended_Scotch),
        Islay_single_malt_Scotch: JSON.parse(response.data[0].Islay_single_malt_Scotch),
        One_Fifty_One_proof_rum: JSON.parse(response.data[0].One_Fifty_One_proof_rum),
        Seven_up: JSON.parse(response.data[0].Seven_up),
        Absinthe: JSON.parse(response.data[0].Absinthe),
        Absolut_citron: JSON.parse(response.data[0].Absolut_citron),
        Creme_de_Mure: JSON.parse(response.data[0].Creme_de_Mure),
        Olive_Brine: JSON.parse(response.data[0].Olive_Brine),
        Pineapple_Syrup: JSON.parse(response.data[0].Pineapple_Syrup),
        St_Germain: JSON.parse(response.data[0].St_Germain),
        Lavender: JSON.parse(response.data[0].Lavender),
        Whiskey: JSON.parse(response.data[0].Whiskey),
        Whisky: JSON.parse(response.data[0].Whisky),
        ingredientCounter: count
      })
    })
    .catch(error => {
      // handle error
      console.log(error);
    })
    .finally(() => {
      // always executed
    });
  }

  addItemToBar(event){
    // console.log('ingredient is here: ', ingredient);
    let tempCounter = 0
    if (this.state[event.target.id] === false) {
      tempCounter++;
    } else {
      tempCounter--;
    }

    this.setState(prevState => {
      return {ingredientCounter: prevState.ingredientCounter + tempCounter}
   })

    this.setState({
      [event.target.id]: !this.state[event.target.id]

    });
  }

  clearIngredients(){
    this.setState({
      Vodka: false,
      Gin: false,
      Rum: false,
      Tequila: false,
      Scotch: false,
      Absolut_Kurant: false,
      Absolut_Peppar: false,
      Absolut_Vodka: false,
      Advocaat: false,
      Aejo_Rum: false,
      Aftershock: false,
      Agave_Syrup: false,
      Ale: false,
      Allspice: false,
      Almond_Extract: false,
      Almond_Flavoring: false,
      Almond: false,
      Amaretto: false,
      Angelica_Root: false,
      Angostura_Bitters: false,
      Anis: false,
      Anise: false,
      Anisette: false,
      Aperol: false,
      Apfelkorn: false,
      Apple_Brandy: false,
      Apple_Cider: false,
      Apple_Juice: false,
      Apple_Schnapps: false,
      Apple: false,
      Applejack: false,
      Apricot_Brandy: false,
      Apricot_Nectar: false,
      Apricot: false,
      Aquavit: false,
      Asafoetida: false,
      Añejo_Rum: false,
      Bacardi_Limon: false,
      Bacardi: false,
      Baileys_Irish_Cream: false,
      Banana_Liqueur: false,
      Banana_Rum: false,
      Banana_Syrup: false,
      Banana: false,
      Barenjager: false,
      Basil: false,
      Beef_Stock: false,
      Beer: false,
      Benedictine: false,
      Berries: false,
      Bitter_lemon: false,
      Bitters: false,
      Black_Pepper: false,
      Black_Rum: false,
      Black_Sambuca: false,
      Blackberries: false,
      Blackberry_Brandy: false,
      Blackberry_Schnapps: false,
      Blackcurrant_Cordial: false,
      Blackcurrant_Schnapps: false,
      Blackcurrant_Squash: false,
      Blended_Whiskey: false,
      Blue_Curacao: false,
      Blue_Maui: false,
      Blueberries: false,
      Blueberry_Schnapps: false,
      Bourbon: false,
      Brandy: false,
      Brown_Sugar: false,
      Butter: false,
      Butterscotch_Schnapps: false,
      Cachaca: false,
      Calvados: false,
      Campari: false,
      Canadian_Whisky: false,
      Candy: false,
      Cantaloupe: false,
      Caramel_Coloring: false,
      Carbonated_Soft_Drink: false,
      Carbonated_Water: false,
      Cardamom: false,
      Cayenne_Pepper: false,
      Celery_Salt: false,
      Celery: false,
      Chambord_Raspberry_Liqueur: false,
      Champagne: false,
      Cherries: false,
      Cherry_Brandy: false,
      Cherry_Cola: false,
      Cherry_Grenadine: false,
      Cherry_Heering: false,
      Cherry_Juice: false,
      Cherry_Liqueur: false,
      Cherry: false,
      Chocolate_Ice_cream: false,   //Chocolate_Ice-cream
      Chocolate_Liqueur: false,
      Chocolate_Milk: false,
      Chocolate_Syrup: false,
      Chocolate: false,
      Cider: false,
      Cinnamon_Schnapps: false,
      Cinnamon: false,
      Citrus_Vodka: false,
      Clamato_Juice: false,
      Cloves: false,
      Club_Soda: false,
      Coca_Cola: false,  //Coca-Cola
      Cocktail_Onion: false,
      Cocoa_Powder: false,
      Coconut_Cream: false,
      Coconut_Liqueur: false,
      Coconut_Milk: false,
      Coconut_Rum: false,
      Coconut_Syrup: false,
      Coffee_Brandy: false,
      Coffee_Liqueur: false,
      Coffee: false,
      Cognac: false,
      Cointreau: false,
      Cola: false,
      Cold_Water: false,
      Condensed_Milk: false,
      Coriander: false,
      Corn_Syrup: false,
      Cornstarch: false,
      Corona: false,
      Cranberries: false,
      Cranberry_Juice: false,
      Cranberry_Liqueur: false,
      Cranberry_Vodka: false,
      Cream_of_Coconut: false,
      Cream_Sherry: false,
      Cream_Soda: false,
      Cream: false,
      Creme_De_Almond: false,
      Creme_De_Banane: false,
      Creme_De_Cacao: false,
      Creme_De_Cassis: false,
      Creme_De_Noyaux: false,
      Creme_Fraiche: false,
      Crown_Royal: false,
      Crystal_Light: false,
      Cucumber: false,
      Cumin_Powder: false,
      Cumin_Seed: false,
      Curacao: false,
      Cynar: false,
      Daiquiri_Mix: false,
      Dark_Chocolate: false,
      Dark_Creme_De_Cacao: false,
      Dark_Rum: false,
      Dark_Soy_Sauce: false,
      Demerara_Sugar: false,
      Dr_Pepper: false,  //Dr._Pepper
      Drambuie: false,
      Dried_Oregano: false,
      Dry_Vermouth: false,
      Dubonnet_Blanc: false,
      Dubonnet_Rouge: false,
      Egg_White: false,
      Egg_Yolk: false,
      Egg: false,
      Eggnog: false,
      Erin_Cream: false,
      Espresso: false,
      Everclear: false,
      Fanta: false,
      Fennel_Seeds: false,
      Firewater: false,
      Flaked_Almonds: false,
      Food_Coloring: false,
      Forbidden_Fruit: false,
      Frangelico: false,
      Fresca: false,
      Fresh_Basil: false,
      Fresh_Lemon_Juice: false,
      Fruit_Juice: false,
      Fruit_Punch: false,
      Fruit: false,
      Galliano: false,
      Garlic_Sauce: false,
      Gatorade: false,
      Ginger_Ale: false,
      Ginger_Beer: false,
      Ginger: false,
      Glycerine: false,
      Godiva_Liqueur: false,
      Gold_rum: false,
      Gold_Tequila: false,
      Goldschlager: false,
      Grain_Alcohol: false,
      Grand_Marnier: false,
      Granulated_Sugar: false,
      Grape_juice: false,
      Grape_soda: false,
      Grapefruit_Juice: false,
      Grapes: false,
      Green_Chartreuse: false,
      Green_Creme_de_Menthe: false,
      Green_Ginger_Wine: false,
      Green_Olives: false,
      Grenadine: false,
      Ground_Ginger: false,
      Guava_juice: false,
      Guinness_stout: false,
      Guinness: false,
      Half_and_half: false,  //Half-and-half
      Hawaiian_punch: false,
      Hazelnut_liqueur: false,
      Heavy_cream: false,
      Honey: false,
      Hooch: false,
      Hot_Chocolate: false,
      Hot_Damn: false,
      Hot_Sauce: false,
      Hpnotiq: false,
      Ice_Cream: false,  //Ice-Cream
      Ice: false,
      Iced_tea: false,
      Irish_cream: false,
      Irish_Whiskey: false,
      Jack_Daniels: false,
      Jello: false,
      Jelly: false,
      Jagermeister: false,
      Jim_Beam: false,
      Johnnie_Walker: false,
      Kahlua: false,
      Key_Largo_Schnapps: false,
      Kirschwasser: false,
      Kiwi_liqueur: false,
      Kiwi: false,
      Kool_Aid: false,  //Kool-Aid
      Kummel: false,
      Lager: false,
      Lemon_Juice: false,
      Lemon_Peel: false,
      Lemon_soda: false,
      Lemon_vodka: false,
      Lemon_lime_soda: false,  //Lemon-lime_soda
      lemon_lime: false,    //lemon-lime
      lemon: false,
      Lemonade: false,
      Licorice_Root: false,
      Light_Cream: false,
      Light_Rum: false,
      Lillet: false,
      Lime_juice_cordial: false,
      Lime_Juice: false,
      Lime_liqueur: false,
      Lime_Peel: false,
      Lime_vodka: false,
      Lime: false,
      Limeade: false,
      Madeira: false,
      Malibu_Rum: false,
      Mandarin: false,
      Mandarine_napoleon: false,
      Mango: false,
      Maple_syrup: false,
      Maraschino_cherry_juice: false,
      Maraschino_Cherry: false,
      Maraschino_Liqueur: false,
      Margarita_mix: false,
      Marjoram_leaves: false,
      Marshmallows: false,
      Maui: false,
      Melon_Liqueur: false,
      Melon_Vodka: false,
      Mezcal: false,
      Midori_Melon_Liqueur: false,
      Midori: false,
      Milk: false,
      Mint_syrup: false,
      Mint: false,
      Mountain_Dew: false,
      Nutmeg: false,
      Olive_Oil: false,
      Olive: false,
      Onion: false,
      Orange_Bitters: false,
      Orange_Curacao: false,
      Orange_Juice: false,
      Orange_liqueur: false,
      Orange_Peel: false,
      Orange_rum: false,
      Orange_Soda: false,
      Orange_spiral: false,
      Orange_vodka: false,
      Orange: false,
      Oreo_cookie: false,
      Orgeat_Syrup: false,
      Ouzo: false,
      Oyster_Sauce: false,
      Papaya_juice: false,
      Papaya: false,
      Parfait_amour: false,
      Passion_fruit_juice: false,
      Passion_fruit_syrup: false,
      Passoa: false,
      Peach_brandy: false,
      Peach_juice: false,
      Peach_liqueur: false,
      Peach_Nectar: false,
      Peach_Schnapps: false,
      Peach_Vodka: false,
      Peach: false,
      Peachtree_schnapps: false,
      Peanut_Oil: false,
      Pepper: false,
      Peppermint_extract: false,
      Peppermint_Schnapps: false,
      Pepsi_Cola: false,
      Pernod: false,
      Peychaud_bitters: false,
      Pina_colada_mix: false,
      Pineapple_Juice: false,
      Pineapple_rum: false,
      Pineapple_vodka: false,
      Pineapple_orange_banana_juice: false,   //Pineapple-orange-banana_juice
      Pineapple: false,
      Pink_lemonade: false,
      Pisang_Ambon: false,
      Pisco: false,
      Plain_Chocolate: false,
      Plain_Flour: false,
      Plums: false,
      Port: false,
      Powdered_Sugar: false,
      Purple_passion: false,
      Raisins: false,
      Raspberry_cordial: false,
      Raspberry_Jam: false,
      Raspberry_Juice: false,
      Raspberry_Liqueur: false,
      Raspberry_schnapps: false,
      Raspberry_syrup: false,
      Raspberry_Vodka: false,
      Red_Chile_Flakes: false,
      Red_Chili_Flakes: false,
      Red_Hot_Chili_Flakes: false,
      Red_Wine: false,
      Rhubarb: false,
      Ricard: false,
      Rock_Salt: false,
      Root_beer_schnapps: false,
      Root_beer: false,
      Roses_sweetened_lime_juice: false,
      Rosewater: false,
      Rumple_Minze: false,
      Rye_Whiskey: false,
      Sake: false,
      Salt: false,
      Sambuca: false,
      Sarsaparilla: false,
      Schnapps: false,
      Schweppes_Lemon: false,
      Schweppes_Russchian: false,
      Sherbet: false,
      Sherry: false,
      Sirup_of_roses: false,
      Sloe_Gin: false,
      Soda_Water: false,
      Sour_Apple_Pucker: false,
      Sour_Mix: false,
      Southern_Comfort: false,
      Soy_Milk: false,
      Soy_Sauce: false,
      Soya_Milk: false,
      Soya_Sauce: false,
      Spiced_Rum: false,
      Sprite: false,
      Squeezed_Orange: false,
      Squirt: false,
      Strawberries: false,
      Strawberry_juice: false,
      Strawberry_liqueur: false,
      Strawberry_Schnapps: false,
      Strawberry_syrup: false,
      Sugar_Syrup: false,
      Sugar: false,
      Sunny_delight: false,
      Surge: false,
      Swedish_punsch: false,
      Sweet_and_Sour: false,
      Sweet_Cream: false,
      Sweet_Vermouth: false,
      Tabasco_Sauce: false,
      Tang: false,
      Tawny_port: false,
      Tea: false,
      Tennessee_whiskey: false,
      Tequila_rose: false,
      Tia_Maria: false,
      Tomato_Juice: false,
      Tomato: false,
      Tonic_Water: false,
      Triple_Sec: false,
      Tropicana: false,
      Tuaca: false,
      Vanilla_extract: false,
      Vanilla_Ice_Cream: false,   //Vanilla_Ice-Cream
      Vanilla_liqueur: false,
      Vanilla_schnapps: false,
      Vanilla_syrup: false,
      Vanilla_vodka: false,
      Vanilla: false,
      Vermouth: false,
      Vinegar: false,
      Water: false,
      Watermelon_schnapps: false,
      Whipped_Cream: false,
      Whipping_Cream: false,
      White_chocolate_liqueur: false,
      White_Creme_de_Menthe: false,
      White_grape_juice: false,
      White_port: false,
      White_Rum: false,
      White_Vinegar: false,
      White_Wine: false,
      Wild_Turkey: false,
      Wildberry_schnapps: false,
      Wine: false,
      Worcestershire_Sauce: false,
      Wormwood: false,
      Yeast: false,
      Yellow_Chartreuse: false,
      Yoghurt: false,
      Yukon_Jack: false,
      Zima: false,
      Caramel_Sauce: false,
      Chocolate_Sauce: false,
      Lillet_Blanc: false,
      Peach_Bitters: false,
      Mini_snickers_bars: false,   //Mini-snickers_bars
      Prosecco: false,
      Salted_Chocolate: false,
      Martini_Rosso: false,
      Martini_Bianco: false,
      Martini_Extra_Dry: false,
      Fresh_Lime_Juice: false,
      Fresh_Mint: false,
      Rosemary: false,
      Habanero_Peppers: false,
      Ilegal_Joven_mezcal: false,
      Elderflower_cordial: false,
      Rosso_Vermouth: false,
      Creme_de_Violette: false,
      Cocchi_Americano: false,
      White_Vermouth: false,
      Dry_Curacao: false,
      Nocino: false,
      Averna: false,
      Ramazzotti: false,
      Fernet_Branca: false,   //Fernet-Branca
      Allspice_Dram: false,
      Falernum: false,
      Singani: false,
      Arrack: false,
      Blackstrap_rum: false,
      Ginger_Syrup: false,
      Honey_syrup: false,
      Blended_Scotch: false,
      Islay_single_malt_Scotch: false,
      One_Fifty_One_proof_rum: false,    //151_proof_rum
      Seven_up: false,   ///7-up
      Absinthe: false,
      Absolut_citron: false,
      Creme_de_Mure: false,
      Olive_Brine: false,
      Pineapple_Syrup: false,
      St_Germain: false,    //St._Germain
      Lavender: false,
      Whiskey: false,
      Whisky: false,
      ingredientCounter: 0
    })
  }

  renderDrinkList(){
    let params = [];
    for (var key in this.state) {
      if(this.state[key] === true || this.state[key] === 'true') {
        params.push(key)
      }
    }

    let searchAllAlcoholicDrinks = 'https://www.thecocktaildb.com/api/json/v1/1/filter.php?a=Alcoholic';
    let searchDrinksByParameters = 'https://www.thecocktaildb.com/api/json/v2/9973533/filter.php?i=' + params;

    axios.get((params.length > 0) ? searchDrinksByParameters : searchAllAlcoholicDrinks)
    .then(response => {
      // handle success
      console.log('response: ', response)
      this.setState({
        listOfDrinks: response.data.drinks
      })

      // }
    })
    .catch(error => {
      // handle error
      console.log(error);
      // this.setState({
      //   listOfDrinks: [{strDrink: "155 Belmont", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg", idDrink: "15346"}]
      // })
    })
    .then(() => {
      // always executed
    });

    this.setState({
      Page: 'DrinkList'
    })
  }

  renderLanding(){
    this.setState({
      Page: 'Landing',
      filterDrinks: ''
    })
  }

  renderCompleteDrinkInfo(idNumber){
    let searchForDrink = `https://www.thecocktaildb.com/api/json/v2/9973533/lookup.php?i=` + idNumber;

    axios.get(searchForDrink)
    .then( (response) => {
      // handle success
      this.setState({
        selectedItem: response.data.drinks[0]
      })
    })
    .catch( (error) => {
      // handle error
      console.log(error);
    })
    .then( () => {
      // always executed
    });

    this.setState({
      Page: 'CompleteDrinkInfo'
    })
  }

  findRandomDrink(){
    axios.get('https://www.thecocktaildb.com/api/json/v1/1/random.php')
    .then( (response) => {

      console.log(response.data.drinks[0])
      this.setState({
        selectedItem: response.data.drinks[0]

      })

    })
    .catch( (error) => {
      // handle error
      console.log(error);
    })
    .then( () => {
      // always executed
    });

    this.setState({
      Page: 'CompleteDrinkInfo'
    })

  }

  findTopCocktails(){
    axios.get('https://www.thecocktaildb.com/api/json/v2/9973533/popular.php')
    .then( (response) => {

      console.log(response.data)
      this.setState({
        listOfDrinks: response.data.drinks

      })

    })
    .catch( (error) => {
      // handle error
      console.log(error);
    })
    .then( () => {
      // always executed
    });
    this.setState({
      Page: 'DrinkList'
    })

  }

  handleFilterChange(event){
    this.setState({
      filterDrinks: event.target.value
    })
    // this.props.onChange(event.target.value)
  }

  saveIngredients(){
    // console.log('saving your ingredients to db');
    axios.post('/ingredients', {
      ingredientData: this.state
    })
    .then(function (response) {
      // console.log(response);
    })
    .catch(function (error) {
      // console.log(error);
    });

  }

  // getFullDrinkInfo(){
  //   console.log('get full drink info clicked!')
  // }

  render() {
    if (this.state.Page === 'Landing') {
      return (
        <div>
          {/* <h1>
            Open Bar
          </h1> */}
          <IngredientSelector
            addItemToBar={this.addItemToBar}
            ingredients={this.state}
            handleFilterChange={this.handleFilterChange}
            renderDrinkList={this.renderDrinkList}
            saveIngredients={this.saveIngredients}
            clearIngredients={this.clearIngredients}
            findRandomDrink={this.findRandomDrink}
            findTopCocktails={this.findTopCocktails}/>
        </div>
      )
    } else if (this.state.Page === 'DrinkList') {
      return (
        <div>
          {/* <h1>
            Open Bar
          </h1> */}
          <DrinkList
          renderLanding={this.renderLanding}
          selectedItem={this.state.selectedItem}
          listOfDrinks={this.state.listOfDrinks}
          renderCompleteDrinkInfo={this.renderCompleteDrinkInfo}/>
        </div>
      )
    } else if (this.state.Page === 'CompleteDrinkInfo') {
      return (
        <div>
          {/* <h1>
          Open Bar
          </h1> */}
          <CompleteDrinkInfo renderLanding={this.renderLanding} selectedItem={this.state.selectedItem} renderDrinkList={this.renderDrinkList}/>
        </div>
      )
    }
  }
}

export default Landing;